ALTER TABLE AtooCGA40..ADHERENTS ADD NUM_ADH_OLD varchar(50)  null 
ALTER TABLE AtooCGA40..ADHERENTS ADD ID_BUREAU_OLD bigint
ALTER TABLE AtooCGA40..CABINETS_COMPTABLES ADD REF_CAB_OLD varchar(50)  null
ALTER TABLE AtooCGA40..BUREAUX ADD CODE_BUR_OLD varchar(50)  null
ALTER TABLE AtooCGA40..BUREAUX ADD ID_BUR_OLD varchar(50)  null
ALTER TABLE AtooCGA40..EXPERTS ADD ID_EXP_OLD varchar(50)  null
ALTER TABLE AtooCGA40..ASSOCIES ADD ID_ASS_OLD varchar(50)  null
ALTER TABLE AtooCGA40..EXERCE_POUR ADD ID_EXP_OLD varchar(50)  null
ALTER TABLE AtooCGA40..EXERCE_POUR ADD ID_BUR_OLD varchar(50)  null
ALTER TABLE AtooCGA40..COLLABORATEURS ADD ID_COL_OLD varchar(50)  null
ALTER TABLE AtooCGA40..COLLABORATEURS ADD ID_BUR_OLD varchar(50)  null

/*
ALTER TABLE AtooCGA40..ADHERENTS DROP column NUM_ADH_OLD
ALTER TABLE AtooCGA40..ADHERENTS DROP column ID_BUREAU_OLD
ALTER TABLE AtooCGA40..CABINETS_COMPTABLES DROP column REF_CAB_OLD
ALTER TABLE AtooCGA40..BUREAUX DROP column CODE_BUR_OLD
ALTER TABLE AtooCGA40..BUREAUX DROP column ID_BUR_OLD
ALTER TABLE AtooCGA40..EXPERTS DROP column ID_EXP_OLD
ALTER TABLE AtooCGA40..ASSOCIES DROP column ID_ASS_OLD
ALTER TABLE AtooCGA40..EXERCE_POUR DROP column ID_EXP_OLD
ALTER TABLE AtooCGA40..EXERCE_POUR DROP column ID_BUR_OLD
ALTER TABLE AtooCGA40..COLLABORATEURS DROP column ID_COL_OLD
ALTER TABLE AtooCGA40..COLLABORATEURS DROP column ID_BUR_OLD
*/



