/*    ==Paramètres de script==

    Version du serveur source : SQL Server 2014 (12.0.4237)
    Édition du moteur de base de données source : Microsoft SQL Server Enterprise Edition
    Type du moteur de base de données source : SQL Server autonome

    Version du serveur cible : SQL Server 2014
    Édition du moteur de base de données cible : Microsoft SQL Server Enterprise Edition
    Type du moteur de base de données cible : SQL Server autonome
*/

USE [master]
GO

/****** Object:  Database [AtooPivot]    Script Date: 30/08/2017 18:01:47 ******/
CREATE DATABASE [AtooPivot]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AtooPivot', FILENAME = N'C:\Cegid\FusionLDG\BDD CGA40\AtooPivot.mdf' , SIZE = 24576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AtooPivot_log', FILENAME = N'C:\Cegid\FusionLDG\BDD CGA40\AtooPivot_log.ldf' , SIZE = 52416KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AtooPivot] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AtooPivot].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AtooPivot] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AtooPivot] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AtooPivot] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AtooPivot] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AtooPivot] SET ARITHABORT OFF 
GO

ALTER DATABASE [AtooPivot] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AtooPivot] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AtooPivot] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AtooPivot] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AtooPivot] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AtooPivot] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AtooPivot] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AtooPivot] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AtooPivot] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AtooPivot] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AtooPivot] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AtooPivot] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AtooPivot] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AtooPivot] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AtooPivot] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AtooPivot] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AtooPivot] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AtooPivot] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AtooPivot] SET  MULTI_USER 
GO

ALTER DATABASE [AtooPivot] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AtooPivot] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AtooPivot] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AtooPivot] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AtooPivot] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AtooPivot] SET  READ_WRITE 
GO

