BEGIN TRAN

SET NOCOUNT ON
--I] Mise en place tables de travail
--     A] SUPPRESSION DES TABLES TEMPORAIRES

-- supprime table temporaire adhérents
if object_id('tempdb..#ADHERENTS_TEMP') is not null
DROP table #ADHERENTS_TEMP

-- supprime table temporaire personnes
if object_id('tempdb..#PERSONNES_TEMP') is not null
DROP table #PERSONNES_TEMP

-- supprime table temporaire fin compte plan
if object_id('tempdb..#FIN_COMPT_PLAN_TEMP') is not null
DROP table #FIN_COMPT_PLAN_TEMP 

-- supprime tablex temporaire fin tiers
if object_id('tempdb..#FIN_TIERS_TEMP') is not null
DROP table #FIN_TIERS_TEMP

-- supprime tablex temporaire etablissements
if object_id('tempdb..#ETABLISSEMENTS_TEMP') is not null
DROP table #ETABLISSEMENTS_TEMP

-- supprime tablex temporaire adresses
if object_id('tempdb..#ADRESSES_TEMP') is not null
DROP table #ADRESSES_TEMP

--     B] CREATION TABLE TEMPORAIRES

-- création table temporaire adherents

select * 
into #ADHERENTS_TEMP 
from AtooCGA40..ADHERENTS

-- création table temporaire personnes

select * 
into #PERSONNES_TEMP 
from AtooCGA40..PERSONNES

-- création table temporaire adresses 

select * 
into #ADRESSES_TEMP 
from AtooCGA40..ADRESSES

-- création table temporaire fin compte plan

select * 
into #FIN_COMPT_PLAN_TEMP
from AtooCGA40..FIN_COMPTES_PLAN

-- création table temporaire fin tiers

select * 
into #FIN_TIERS_TEMP
from AtooCGA40..FIN_TIERS

-- création table temporaire fin tiers

select * 
into #ETABLISSEMENTS_TEMP
from AtooCGA40..ETABLISSEMENTS


--     D] CREATION COLONNE PROVENANCE

-- création colonne provenance données adherents

ALTER TABLE #ADHERENTS_TEMP ADD is_AtooCGA40 bit not null default 0
ALTER TABLE #ADHERENTS_TEMP ADD ID_ADHERENT_OLD bigint
ALTER TABLE #ADHERENTS_TEMP ADD ID_BUR_OLD bigint

-- création colonne provenance données adherents

ALTER TABLE #PERSONNES_TEMP ADD is_AtooCGA40 bit not null default 0

-- création colonne provenance données adherents

ALTER TABLE #ADRESSES_TEMP ADD ID_OLD_ADRESSE bigint
ALTER TABLE #ADRESSES_TEMP ADD is_AtooCGA40 bit not null default 0

-- création colonne provenance données adherents

ALTER TABLE #FIN_COMPT_PLAN_TEMP ADD is_AtooCGA40 bit not null default 0

-- création colonne provenance données adherents

ALTER TABLE #FIN_TIERS_TEMP ADD is_AtooCGA40 bit not null default 0

-- création colonne provenance données adherents

ALTER TABLE #ETABLISSEMENTS_TEMP ADD is_AtooCGA40 bit not null default 0


--     E] DECLARATION VARIABLE


--ADHERENTS
declare @CUR_ID_ADHERENT bigint
declare @CUR_NUMERO_ADHERENT varchar(10)
declare @CUR_ID_PERSONNE bigint
declare @CUR_ID_ADRESSE_CORRESPONDANCE bigint
declare @CUR_ID_ADRESSE_JOURNAL bigint
declare @CUR_ID_BUREAU bigint
declare @CUR_ID_EXPERT bigint
declare @CUR_ID_ANALYSTE_GESTION int
declare @CUR_ID_ANALYSTE_ECV int
declare @CUR_ID_GESTION_ADMIN int
declare @CUR_ID_COLLABORATEUR bigint
declare @CUR_ID_MOTIF_ADHESION tinyint
declare @CUR_ID_STAT_ADHESION tinyint
declare @CUR_HORS_DELAI bit
declare @CUR_ID_COTISATION tinyint
declare @CUR_ID_FORME_JURIDIQUE char(4)
declare @CUR_CAT_IMPOSITION tinyint
declare @CUR_REGIME_FISCAL tinyint
declare @CUR_REGIME_IMPOSITION char(2)
declare @CUR_DATE_ADHESION smalldatetime
declare @CUR_DATE_DEBUT_ACTIVITE smalldatetime
declare @CUR_DATE_DEBUT_1ER_EXO smalldatetime
declare @CUR_DATE_FIN_1ER_EXO smalldatetime
declare @CUR_DF_PRO_EXIST bit
declare @CUR_OBSERVATION varchar(500)
declare @CUR_ABT_JOURNAL bit
declare @CUR_ID_SIT_FAM char(1)
declare @CUR_ID_STAT_CONJOINT tinyint
declare @CUR_ID_ADRESSE_ALTERNATIVE bigint
declare @CUR_REGISTRE_COMMERCE varchar(35)
declare @CUR_REGISTRE_METIERS varchar(35)
declare @CUR_ID_MOTIF_RADIATION tinyint
declare @CUR_ID_CASIER int
declare @CUR_DATE_EFFET_RADIATION smalldatetime
declare @CUR_DEFAULT_NAF_STAT varchar(6)
declare @CUR_COMMENTAIRE_RADIATION varchar(50)
declare @CUR_ID_TIERS_CLIENT bigint
declare @CUR_DROIT_ENTREE bit
declare @CUR_DATE_RADIATION_ADM smalldatetime
declare @CUR_ID_MOTIF_EXONERATION_DROIT_ENTREE tinyint
declare @CUR_ID_PROFILE_ADHESION tinyint
declare @CUR_DATE_CREATION smalldatetime
declare @CUR_LISTE_ANOMALIES varchar(1024)
declare @CUR_ID_STATUT_ADM tinyint
declare @CUR_ID_AGENCE tinyint
declare @CUR_NUMERO_ADHERENT_AUXILIAIRE varchar(10)
declare @CUR_DATE_DERNIERE_MODIFICATION smalldatetime
declare @CUR_ID_INTERLOCULTEUR_DERNIERE_MODIFICATION int
declare @CUR_DESTINATAIRE_ATTESTATION tinyint
declare @CUR_NOMENCLATURE char(1)
declare @CUR_ID_CASIER_ATT int
declare @CUR_TYPE_SUIVI tinyint
declare @CUR_ID_ANALYSTE_REG int
declare @CUR_ID_CASIER_ATT_SECONDAIRE int
declare @CUR_GUID_ADHERENT char (36)
declare @CUR_HAS_DOSSIER_PGI bit 
declare @CUR_NB_ASSOCIES int
declare @CUR_NB_ASSOCIES_ACTIFS int
declare @CUR_ID_ACTEUR_TELETRANS tinyint
declare @CUR_ID_PARTENAIRE_SIE int
declare @CUR_ROF varchar (13)
declare @CUR_TENUE_COMPTA_TTC bit 
declare @CUR_ACTIVITE_NON_SOUMISE_TVA bit
declare @CUR_CADMINI varchar (1)
declare @CUR_FORMEJURIDIQUE varchar (1)
declare @CUR_IS_EIRL bit
declare @CUR_DATE_OPTION_IS smalldatetime
declare @CUR_CODE_TENUE_COMPTA varchar(4)
declare @CUR_CODE_EXIGIBILITE_TVA varchar (4)
declare @CUR_CODE_REGIME_TVA varchar (5)
declare @CUR_ID_BASE_IMPOSITION smallint
declare @CUR_FRANCHISE_TVA bit
declare @CUR_GESTION_TVA_COR bit
declare @CUR_ROF_TVA varchar(20)
declare @CUR_ASSUJETTI_PARTIEL_TVA bit
declare @CUR_WEB_BLOCAGE_ACCES bit
declare @CUR_WEB_OPTION_ECV bit
declare @CUR_WEB_OPTION_DG bit
declare @CUR_WEB_OPTION_CRM bit
declare @CUR_ROF_CVAE varchar(20)
declare @CUR_TVA_NB_PERIODES_MANQUANTES int
declare @CUR_MEDECIN_CODE_SECTEUR varchar (2)
declare @CUR_SCM_MEMBRE bit
declare @CUR_TVA_PRECOMPTE bit
declare @CUR_ACRE bit
declare @CUR_ACRE_DEBUT smalldatetime
declare @CUR_ACRE_FIN smalldatetime 
declare @CUR_EXO_CET bit 
declare @CUR_EXO_AF bit
declare @CUR_EXO_CSG_CRDS bit
declare @CUR_EXO_RETRAITE bit
declare @CUR_EXO_MALADIE bit
declare @CUR_ACTIVITE_ACCESSOIRE bit
declare @CUR_TVA_DES bit
declare @CUR_DIPLOME_VERIFIE tinyint
declare @CUR_DIPLOME_OBTENTION smallint
declare @CUR_LOGICIEL_COMPTABLE varchar (60)
declare @CUR_ZFU_VERIFIEE bit
declare @CUR_ZFU_DATE_DEBUT smalldatetime
declare @CUR_ZFU_DATE_FIN smalldatetime
declare @CUR_ZFU_GENERATION tinyint
declare @CUR_WEB_BLOCAGE_SAISIE_DF bit
declare @CUR_OBSERVATION_TVA varchar(4000)
declare @CUR_LISTE_LOCAUX varchar(max)
declare @CUR_DATE_OBTENTION_LOC smalldatetime
declare @CUR_ROF_CFE varchar(20)
declare @CUR_WEB_DESACTIVATION_NOTIFICATION_MAIL bit
declare @CUR_EXCLUSION_PORTAIL_TVA bit
declare @CUR_EXCLUSION_EXPORT_TVA_FCGA_OBS bit
declare @CUR_NB_OBLIGATIONS_FISCALES_LOC int
declare @CUR_SOURCE_DOCUMENT_EPS varchar(3)
declare @CUR_SOURCE_COMPTABILITE_EPS varchar(3)
declare @COMPTABILITE_INFORMATISEE bit

--PERSONNES

declare @CUR_ID_TITRE int
declare @CUR_RAISON_SOCIALE varchar(50)
declare @CUR_NOM varchar(40)
declare @CUR_PRENOM varchar(40)
declare @CUR_TELEPHONE_FIXE_PERSO varchar(18)
declare @CUR_TELEPHONE_MOBILE_PERSO varchar(18)
declare @CUR_TELEPHONE_FAX_PERSO varchar(18)
declare @CUR_EMAIL_PERSO varchar(100)
declare @CUR_TYPE_PERSONNE int
declare @CUR_ID_ADRESSE_PERSO bigint
declare @CUR_DATE_NAISSANCE smalldatetime
declare @CUR_SITE_WEB varchar(100)
declare @CUR_LOGIN_CGA varchar(15)
declare @CUR_PASSWORD_CGA varchar(15)
declare @CUR_TELEPHONE_ALTERNATIVE_PERSO varchar(18)
declare @CUR_NOM_JEUNE_FILLE varchar (40)
declare @CUR_MUST_CHANGED_PASSWORD bit
declare @CUR_ID_STATUT_EMAIL tinyint
declare @CUR_EMAIL_CCI_LIST varchar (2000)

--ADRESSES DOM
declare @CUR_ID_ADRESSE_DOM bigint
declare @CUR_IDENTITE_DESTINATAIRE_DOM varchar(60)
declare @CUR_COMPLEMENT_IDENTIFICATION_DOM varchar(60)
declare @CUR_COMPLEMENT_ADRESSE_DOM varchar(60)
declare @CUR_NUMERO_VOIE_DOM varchar(10)
declare @CUR_TYPE_VOIE_DOM int
declare @CUR_LIBELLE_VOIE_DOM varchar(60)
declare @CUR_COMPLEMENT_ADRESSE_2_DOM varchar(60)
declare @CUR_CP_DOM char(5)
declare @CUR_INSEE_DOM char(5)
declare @CUR_INTERNATIONALE_DOM bit
declare @CUR_COMPLEMENT_INTERNATIONAL_DOM varchar(60)
declare @CUR_ID_PAYS_DOM int

--ADRESSES PRO
declare @CUR_ID_ADRESSE_PRO bigint
declare @CUR_IDENTITE_DESTINATAIRE_PRO varchar(60)
declare @CUR_COMPLEMENT_IDENTIFICATION_PRO varchar(60)
declare @CUR_COMPLEMENT_ADRESSE_PRO varchar(60)
declare @CUR_NUMERO_VOIE_PRO varchar(10)
declare @CUR_TYPE_VOIE_PRO int
declare @CUR_LIBELLE_VOIE_PRO varchar(60)
declare @CUR_COMPLEMENT_ADRESSE_2_PRO varchar(60)
declare @CUR_CP_PRO char(5)
declare @CUR_INSEE_PRO char(5)
declare @CUR_INTERNATIONALE_PRO bit
declare @CUR_COMPLEMENT_INTERNATIONAL_PRO varchar(60)
declare @CUR_ID_PAYS_PRO int

--FIN_COMPTES_PLAN
declare @CUR_COMPTE varchar(8)
declare @CUR_LIBELLE varchar(60)
declare @CUR_COMPTE_EXTERNE varchar(8)

--FIN_TIERS
declare @CUR_ID_TIERS bigint
declare @CUR_TYPE_TIERS char(2)
declare @CUR_SOLDE money
declare @CUR_AUTOFACTURATION bit
declare @CUR_RIB varchar(23)
declare @CUR_INTRACOMMUNAUTAIRE varchar(16)
declare @CUR_TITULAIRE_COMPTE varchar(50)
declare @CUR_DOMICILIATION varchar(40)
declare @CUR_AUTORISATION_PRELEVEMENT bit
declare @CUR_ID_PROFIL_FRS tinyint
declare @CUR_MODE_REGLEMENT_PAR_DEFAUT char(1)
declare @CUR_CHRONO_AUTOFACTURATION int
declare @CUR_ID_BLOCAGE_FACT tinyint
declare @CUR_ID_DELAI_REGLEMENT tinyint
declare @CUR_DATE_DEBUT_MANDAT_AUTOFACTURATION smalldatetime
declare @CUR_DATE_FIN_MANDAT_AUTOFACTURATION smalldatetime
declare @CUR_ADMINISTRATEUR bit
declare @CUR_EXONERATION_TVA bit
declare @CUR_PROFESSION varchar(100)
declare @CUR_SOLDE_TC money
declare @CUR_IBAN varchar(34)
declare @CUR_BIC varchar(11)
declare @CUR_IBAN_ORIGINE varchar(35)
declare @CUR_MANDAT_SEPA varchar(35)
declare @CUR_DATE_SIGNATURE_MANDAT_SEPA smalldatetime
declare @CUR_DATE_PREMIER_PRELEVEMENT smalldatetime
declare @CUR_MANDAT_SEPA_ORIGINE varchar(35)


--ETABLISSEMENTS
declare @CUR_ID_ETABLISSEMENT bigint
declare @CUR_SIRET numeric
declare @CUR_ID_ADRESSE_ETAB bigint
declare @CUR_ETBS_PRINCIPAL bit
declare @CUR_NAF varchar(6)
declare @CUR_ENSEIGNE varchar(50)
declare @CUR_RIVOLI char(4)
declare @CUR_DATE_CREATION_ETAB datetime
declare @CUR_EMAIL_ETAB varchar (100)
declare @CUR_TELEPHONE_FIXE_ETAB varchar (18)
declare @CUR_TELEPHONE_MOBILE_ETAB varchar (18)
declare @CUR_TELEPHONE_FAX_ETAB varchar (18)
declare @CUR_EFFECTIF real
declare @CUR_SURFACE_DE_VENTE int
declare @CUR_ACTIVITE_PRINCIPALE varchar(80)
declare @CUR_ACTIVITE_SECONDAIRE varchar(80)
declare @CUR_TELEPHONE_ALTERNATIVE_ETAB varchar (18)
declare @CUR_ROF_CFE_ETAB varchar(20)

--ADRESSES ALT
declare @CUR_ID_ADRESSE_ALT bigint
declare @CUR_IDENTITE_DESTINATAIRE_ALT varchar(60)
declare @CUR_COMPLEMENT_IDENTIFICATION_ALT varchar(60)
declare @CUR_COMPLEMENT_ADRESSE_ALT varchar(60)
declare @CUR_NUMERO_VOIE_ALT varchar(10)
declare @CUR_TYPE_VOIE_ALT int
declare @CUR_LIBELLE_VOIE_ALT varchar(60)
declare @CUR_COMPLEMENT_ADRESSE_2_ALT varchar(60)
declare @CUR_CP_ALT char(5)
declare @CUR_INSEE_ALT char(5)
declare @CUR_INTERNATIONALE_ALT bit
declare @CUR_COMPLEMENT_INTERNATIONAL_ALT varchar(60)
declare @CUR_ID_PAYS_ALT int

--ADRESSES ETABLISSEMENTS
declare @CUR_ID_ADRESSE_ADR_ETAB bigint
declare @CUR_IDENTITE_DESTINATAIRE_ADR_ETAB varchar(60)
declare @CUR_COMPLEMENT_IDENTIFICATION_ADR_ETAB varchar(60)
declare @CUR_COMPLEMENT_ADRESSE_ADR_ETAB varchar(60)
declare @CUR_NUMERO_VOIE_ADR_ETAB varchar(10)
declare @CUR_TYPE_VOIE_ADR_ETAB int
declare @CUR_LIBELLE_VOIE_ADR_ETAB varchar(60)
declare @CUR_COMPLEMENT_ADRESSE_2_ADR_ETAB varchar(60)
declare @CUR_CP_ADR_ETAB char(5)
declare @CUR_INSEE_ADR_ETAB char(5)
declare @CUR_INTERNATIONALE_ADR_ETAB bit
declare @CUR_COMPLEMENT_INTERNATIONAL_ADR_ETAB varchar(60)
declare @CUR_ID_PAYS_ADR_ETAB int

--REPRISE_CORRESPONDANCE_ID_BUREAUX_AtooCGA40
declare @CUR_ID_BUREAU_NEW bigint
declare @CUR_ID_BUREAU_OLD bigint


-- DECLARATION COMPTEUR

-- cabinets comptables

declare @compteur int
set @compteur=(select max(convert(int,chrono1)) from AtooCGA40.dbo.chronos)
select * from AtooCGA40..chronos

DECLARE ADHERENTS_cursor CURSOR FOR 

select AtooCGA40..adherents.*, AtooCGA40..adherents.ID_BUREAU, ETAB.*, AtooCGA40..fin_tiers.*, AtooCGA40..fin_comptes_plan.*,DOM.*, PRO.*,  AtooCGA40..personnes.*, ALT.*, COR.*
from AtooCGA40..adherents 
left join AtooCGA40..fin_tiers on AtooCGA40..fin_tiers.id_tiers = AtooCGA40..adherents.id_tiers_client
left join AtooCGA40..fin_comptes_plan on AtooCGA40..fin_comptes_plan.compte = AtooCGA40..fin_tiers.compte
left outer join AtooCGA40..personnes on AtooCGA40..adherents.id_personne = AtooCGA40..personnes.id_personne
left outer join AtooCGA40..adresses as DOM on DOM.id_adresse = AtooCGA40..personnes.id_adresse
inner join AtooCGA40..etablissements as ETAB on ETAB.id_adherent = AtooCGA40..adherents.id_adherent
left outer join AtooCGA40..adresses as PRO on PRO.id_adresse = ETAB.id_adresse
left outer join AtooCGA40..adresses as COR on COR.id_adresse = AtooCGA40..adherents.id_adresse_correspondance
left outer join AtooCGA40..adresses as ALT on ALT.id_adresse = AtooCGA40..adherents.ID_ADRESSE_ALTERNATIVE
where ETBS_PRINCIPAL = 1 
order by AtooCGA40..adherents.ID_ADHERENT

--and ID_GESTION_ADMIN is not null
--and ID_GESTION_ADMIN not in (select id_interlocuteur from INTERLOCUTEURS)

--where AtooCGA40..adherents.numero_adherent not in ('99999')
--and NUMERO_ADHERENT = 005366

OPEN ADHERENTS_cursor 

FETCH NEXT FROM ADHERENTS_cursor
       INTO @CUR_ID_ADHERENT,@CUR_NUMERO_ADHERENT,@CUR_ID_PERSONNE,@CUR_ID_ADRESSE_CORRESPONDANCE,@CUR_ID_ADRESSE_JOURNAL,@CUR_ID_BUREAU
       ,@CUR_ID_EXPERT,@CUR_ID_ANALYSTE_GESTION,@CUR_ID_ANALYSTE_ECV,@CUR_ID_GESTION_ADMIN,@CUR_ID_COLLABORATEUR,@CUR_ID_MOTIF_ADHESION
       ,@CUR_ID_STAT_ADHESION,@CUR_HORS_DELAI,@CUR_ID_COTISATION,@CUR_ID_FORME_JURIDIQUE,@CUR_CAT_IMPOSITION,@CUR_REGIME_FISCAL
       ,@CUR_REGIME_IMPOSITION,@CUR_DATE_ADHESION,@CUR_DATE_DEBUT_ACTIVITE,@CUR_DATE_DEBUT_1ER_EXO,@CUR_DATE_FIN_1ER_EXO,@CUR_DF_PRO_EXIST
       ,@CUR_OBSERVATION,@CUR_ABT_JOURNAL,@CUR_ID_SIT_FAM,@CUR_ID_STAT_CONJOINT,@CUR_ID_ADRESSE_ALTERNATIVE,@CUR_REGISTRE_COMMERCE
       ,@CUR_REGISTRE_METIERS,@CUR_ID_MOTIF_RADIATION,@CUR_ID_CASIER,@CUR_DATE_EFFET_RADIATION,@CUR_DEFAULT_NAF_STAT,@CUR_COMMENTAIRE_RADIATION
       ,@CUR_ID_TIERS_CLIENT,@CUR_DROIT_ENTREE,@CUR_DATE_RADIATION_ADM,@CUR_ID_MOTIF_EXONERATION_DROIT_ENTREE,@CUR_ID_PROFILE_ADHESION
       ,@CUR_DATE_CREATION,@CUR_LISTE_ANOMALIES,@CUR_ID_STATUT_ADM,@CUR_ID_AGENCE,@CUR_NUMERO_ADHERENT_AUXILIAIRE,@CUR_DATE_DERNIERE_MODIFICATION
       ,@CUR_ID_INTERLOCULTEUR_DERNIERE_MODIFICATION,@CUR_DESTINATAIRE_ATTESTATION,@CUR_NOMENCLATURE,@CUR_ID_CASIER_ATT,@CUR_TYPE_SUIVI
       ,@CUR_ID_ANALYSTE_REG,@CUR_ID_CASIER_ATT_SECONDAIRE,@CUR_GUID_ADHERENT,@CUR_HAS_DOSSIER_PGI,@CUR_NB_ASSOCIES,@CUR_NB_ASSOCIES_ACTIFS
       ,@CUR_ID_ACTEUR_TELETRANS,@CUR_ID_PARTENAIRE_SIE,@CUR_ROF,@CUR_TENUE_COMPTA_TTC,@CUR_ACTIVITE_NON_SOUMISE_TVA,@CUR_IS_EIRL,@CUR_DATE_OPTION_IS
       ,@CUR_CODE_TENUE_COMPTA,@CUR_CODE_EXIGIBILITE_TVA,@CUR_CODE_REGIME_TVA,@CUR_ID_BASE_IMPOSITION,@CUR_FRANCHISE_TVA,@CUR_GESTION_TVA_COR
       ,@CUR_ROF_TVA,@CUR_ASSUJETTI_PARTIEL_TVA,@CUR_WEB_BLOCAGE_ACCES,@CUR_WEB_OPTION_ECV,@CUR_WEB_OPTION_DG,@CUR_WEB_OPTION_CRM
       ,@CUR_ROF_CVAE,@CUR_TVA_NB_PERIODES_MANQUANTES,@CUR_MEDECIN_CODE_SECTEUR,@CUR_SCM_MEMBRE,@CUR_TVA_PRECOMPTE,@CUR_ACRE,@CUR_ACRE_DEBUT,@CUR_ACRE_FIN
       ,@CUR_EXO_CET,@CUR_EXO_AF,@CUR_EXO_CSG_CRDS,@CUR_EXO_RETRAITE,@CUR_EXO_MALADIE,@CUR_ACTIVITE_ACCESSOIRE,@CUR_TVA_DES,@CUR_DIPLOME_VERIFIE
       ,@CUR_DIPLOME_OBTENTION,@CUR_LOGICIEL_COMPTABLE,@CUR_ZFU_VERIFIEE,@CUR_ZFU_DATE_DEBUT,@CUR_ZFU_DATE_FIN,@CUR_ZFU_GENERATION
       ,@CUR_WEB_BLOCAGE_SAISIE_DF,@CUR_OBSERVATION_TVA,@CUR_LISTE_LOCAUX,@CUR_DATE_OBTENTION_LOC,@CUR_ROF_CFE,@CUR_WEB_DESACTIVATION_NOTIFICATION_MAIL
	   ,@CUR_EXCLUSION_PORTAIL_TVA,@CUR_EXCLUSION_EXPORT_TVA_FCGA_OBS,@CUR_NB_OBLIGATIONS_FISCALES_LOC,@CUR_SOURCE_DOCUMENT_EPS,@CUR_SOURCE_COMPTABILITE_EPS,@COMPTABILITE_INFORMATISEE
	   ,@CUR_ID_BUREAU_OLD
		
	   ,@CUR_ID_ETABLISSEMENT ,@CUR_SIRET,@CUR_ID_ADHERENT,@CUR_ETBS_PRINCIPAL,@CUR_NAF,@CUR_ENSEIGNE,@CUR_DATE_CREATION_ETAB
       ,@CUR_ID_ADRESSE_ETAB,@CUR_RIVOLI,@CUR_EMAIL_ETAB,@CUR_TELEPHONE_FIXE_ETAB,@CUR_TELEPHONE_MOBILE_ETAB,@CUR_TELEPHONE_FAX_ETAB
       ,@CUR_EFFECTIF,@CUR_SURFACE_DE_VENTE,@CUR_ACTIVITE_PRINCIPALE,@CUR_ACTIVITE_SECONDAIRE,@CUR_TELEPHONE_ALTERNATIVE_ETAB,@CUR_ROF_CFE_ETAB
	   
	   ,@CUR_ID_TIERS,@CUR_COMPTE,@CUR_TYPE_TIERS,@CUR_SOLDE,@CUR_AUTOFACTURATION,@CUR_RIB
       ,@CUR_INTRACOMMUNAUTAIRE,@CUR_TITULAIRE_COMPTE,@CUR_DOMICILIATION,@CUR_AUTORISATION_PRELEVEMENT,@CUR_ID_PROFIL_FRS
       ,@CUR_MODE_REGLEMENT_PAR_DEFAUT,@CUR_CHRONO_AUTOFACTURATION,@CUR_ID_BLOCAGE_FACT,@CUR_ID_DELAI_REGLEMENT
       ,@CUR_DATE_DEBUT_MANDAT_AUTOFACTURATION,@CUR_DATE_FIN_MANDAT_AUTOFACTURATION,@CUR_ADMINISTRATEUR,@CUR_EXONERATION_TVA
       ,@CUR_PROFESSION,@CUR_SOLDE_TC,@CUR_IBAN,@CUR_BIC,@CUR_IBAN_ORIGINE,@CUR_MANDAT_SEPA,@CUR_DATE_SIGNATURE_MANDAT_SEPA
       ,@CUR_DATE_PREMIER_PRELEVEMENT,@CUR_MANDAT_SEPA_ORIGINE
       
	   ,@CUR_COMPTE,@CUR_LIBELLE,@CUR_COMPTE_EXTERNE
	   
	   ,@CUR_ID_ADRESSE_DOM,@CUR_IDENTITE_DESTINATAIRE_DOM,@CUR_COMPLEMENT_IDENTIFICATION_DOM,@CUR_COMPLEMENT_ADRESSE_DOM
       ,@CUR_NUMERO_VOIE_DOM,@CUR_TYPE_VOIE_DOM,@CUR_LIBELLE_VOIE_DOM,@CUR_COMPLEMENT_ADRESSE_2_DOM,@CUR_CP_DOM
       ,@CUR_INSEE_DOM,@CUR_INTERNATIONALE_DOM,@CUR_COMPLEMENT_INTERNATIONAL_DOM,@CUR_ID_PAYS_DOM
       
	   ,@CUR_ID_ADRESSE_PRO,@CUR_IDENTITE_DESTINATAIRE_PRO,@CUR_COMPLEMENT_IDENTIFICATION_PRO,@CUR_COMPLEMENT_ADRESSE_PRO
       ,@CUR_NUMERO_VOIE_PRO,@CUR_TYPE_VOIE_PRO,@CUR_LIBELLE_VOIE_PRO,@CUR_COMPLEMENT_ADRESSE_2_PRO,@CUR_CP_PRO
       ,@CUR_INSEE_PRO,@CUR_INTERNATIONALE_PRO,@CUR_COMPLEMENT_INTERNATIONAL_PRO,@CUR_ID_PAYS_PRO
	   
	   ,@CUR_ID_PERSONNE,@CUR_ID_TITRE,@CUR_RAISON_SOCIALE,@CUR_NOM,@CUR_PRENOM,@CUR_TELEPHONE_FIXE_PERSO,@CUR_TELEPHONE_MOBILE_PERSO,@CUR_TELEPHONE_FAX_PERSO
       ,@CUR_EMAIL_PERSO,@CUR_TYPE_PERSONNE,@CUR_ID_ADRESSE_PERSO,@CUR_DATE_NAISSANCE,@CUR_SITE_WEB,@CUR_LOGIN_CGA,@CUR_PASSWORD_CGA
       ,@CUR_TELEPHONE_ALTERNATIVE_PERSO,@CUR_NOM_JEUNE_FILLE,@CUR_MUST_CHANGED_PASSWORD,@CUR_ID_STATUT_EMAIL,@CUR_EMAIL_CCI_LIST

	   ,@CUR_ID_ADRESSE_ALT,@CUR_IDENTITE_DESTINATAIRE_ALT,@CUR_COMPLEMENT_IDENTIFICATION_ALT,@CUR_COMPLEMENT_ADRESSE_ALT
       ,@CUR_NUMERO_VOIE_ALT,@CUR_TYPE_VOIE_ALT,@CUR_LIBELLE_VOIE_ALT,@CUR_COMPLEMENT_ADRESSE_2_ALT,@CUR_CP_ALT
       ,@CUR_INSEE_ALT,@CUR_INTERNATIONALE_ALT,@CUR_COMPLEMENT_INTERNATIONAL_ALT,@CUR_ID_PAYS_ALT
	   
	   ,@CUR_ID_ADRESSE_ADR_ETAB,@CUR_IDENTITE_DESTINATAIRE_ADR_ETAB,@CUR_COMPLEMENT_IDENTIFICATION_ADR_ETAB,@CUR_COMPLEMENT_ADRESSE_ADR_ETAB
       ,@CUR_NUMERO_VOIE_ADR_ETAB,@CUR_TYPE_VOIE_ADR_ETAB,@CUR_LIBELLE_VOIE_ADR_ETAB,@CUR_COMPLEMENT_ADRESSE_2_ADR_ETAB,@CUR_CP_ADR_ETAB
       ,@CUR_INSEE_ADR_ETAB,@CUR_INTERNATIONALE_ADR_ETAB,@CUR_COMPLEMENT_INTERNATIONAL_ADR_ETAB,@CUR_ID_PAYS_ADR_ETAB
	   
	   

WHILE @@FETCH_STATUS = 0
BEGIN

       declare @_ID_ADHERENT as bigint
       declare @_ID_PERSONNE as bigint
       declare @_ID_ADRESSE_DOM as bigint
       declare @_ID_ADRESSE_PRO as bigint
       declare @_ID_ADRESSE_PERSO as bigint
       declare @_ID_ADRESSE_ALT as bigint
       declare @_ID_ADRESSE_ADR_ETAB as bigint
       declare @_ID_TIERS as bigint
       declare @_ID_ETABLISSEMENTS as bigint
       declare @CUR_ID_ETABLISSEMENTS_SECONDAIRES as bigint
       declare @_ID_ETABLISSEMENTS_SECONDAIRES as bigint
       

       -- Adhérents

       set @compteur=@compteur + 1

       INSERT INTO #ADHERENTS_TEMP
       (NUMERO_ADHERENT, ID_ADHERENT_OLD, NUM_ADH_OLD, ID_PERSONNE,ID_ADRESSE_CORRESPONDANCE,ID_ADRESSE_JOURNAL,ID_BUREAU
          ,ID_EXPERT,ID_ANALYSTE_GESTION,ID_ANALYSTE_ECV,ID_GESTION_ADMIN,ID_COLLABORATEUR,ID_MOTIF_ADHESION
              ,ID_STAT_ADHESION,HORS_DELAI,ID_COTISATION,ID_FORME_JURIDIQUE,CAT_IMPOSITION,REGIME_FISCAL
       ,REGIME_IMPOSITION,DATE_ADHESION,DATE_DEBUT_ACTIVITE,DATE_DEBUT_1ER_EXO,DATE_FIN_1ER_EXO,DF_PRO_EXIST
              ,OBSERVATION,ABT_JOURNAL,ID_SIT_FAM,ID_STAT_CONJOINT,ID_ADRESSE_ALTERNATIVE,REGISTRE_COMMERCE
       ,REGISTRE_METIERS,ID_MOTIF_RADIATION,ID_CASIER,DATE_EFFET_RADIATION,DEFAULT_NAF_STAT,COMMENTAIRE_RADIATION
       ,ID_TIERS_CLIENT,DROIT_ENTREE,DATE_RADIATION_ADM,ID_MOTIF_EXONERATION_DROIT_ENTREE,ID_PROFILE_ADHESION
       ,DATE_CREATION,LISTE_ANOMALIES,ID_STATUT_ADM,ID_AGENCE,NUMERO_ADHERENT_AUXILIAIRE,DATE_DERNIERE_MODIFICATION
       ,ID_INTERLOCULTEUR_DERNIERE_MODIFICATION,DESTINATAIRE_ATTESTATION,NOMENCLATURE,ID_CASIER_ATT,TYPE_SUIVI
       ,ID_ANALYSTE_REG,ID_CASIER_ATT_SECONDAIRE,GUID_ADHERENT,HAS_DOSSIER_PGI,NB_ASSOCIES,NB_ASSOCIES_ACTIFS
       ,ID_ACTEUR_TELETRANS,ID_PARTENAIRE_SIE,ROF,TENUE_COMPTA_TTC,ACTIVITE_NON_SOUMISE_TVA,IS_EIRL,DATE_OPTION_IS
       ,CODE_TENUE_COMPTA,CODE_EXIGIBILITE_TVA,CODE_REGIME_TVA,ID_BASE_IMPOSITION,FRANCHISE_TVA,GESTION_TVA_COR
              ,ROF_TVA,ASSUJETTI_PARTIEL_TVA,WEB_BLOCAGE_ACCES,WEB_OPTION_ECV,WEB_OPTION_DG,WEB_OPTION_CRM
       ,ROF_CVAE,TVA_NB_PERIODES_MANQUANTES,MEDECIN_CODE_SECTEUR,SCM_MEMBRE,TVA_PRECOMPTE,ACRE,ACRE_DEBUT,ACRE_FIN
           ,EXO_CET,EXO_AF,EXO_CSG_CRDS,EXO_RETRAITE,EXO_MALADIE,ACTIVITE_ACCESSOIRE,TVA_DES,DIPLOME_VERIFIE
              ,DIPLOME_OBTENTION,LOGICIEL_COMPTABLE,ZFU_VERIFIEE,ZFU_DATE_DEBUT,ZFU_DATE_FIN,ZFU_GENERATION
       ,WEB_BLOCAGE_SAISIE_DF,OBSERVATION_TVA,LISTE_LOCAUX,DATE_OBTENTION_LOC,ROF_CFE,WEB_DESACTIVATION_NOTIFICATION_MAIL
              ,EXCLUSION_PORTAIL_TVA,EXCLUSION_EXPORT_TVA_FCGA_OBS,NB_OBLIGATIONS_FISCALES_LOC,SOURCE_DOCUMENT_EPS,SOURCE_COMPTABILITE_EPS,COMPTABILITE_INFORMATISEE,is_AtooCGA40,ID_BUR_OLD)
       VALUES
       (right ('000000' + convert (varchar, @compteur),6)
       ,@CUR_ID_ADHERENT,@CUR_NUMERO_ADHERENT,@CUR_ID_PERSONNE,@CUR_ID_ADRESSE_CORRESPONDANCE,@CUR_ID_ADRESSE_JOURNAL,@CUR_ID_BUREAU
       ,@CUR_ID_EXPERT,@CUR_ID_ANALYSTE_GESTION,@CUR_ID_ANALYSTE_ECV,@CUR_ID_GESTION_ADMIN,@CUR_ID_COLLABORATEUR,@CUR_ID_MOTIF_ADHESION
       ,@CUR_ID_STAT_ADHESION,@CUR_HORS_DELAI,@CUR_ID_COTISATION,@CUR_ID_FORME_JURIDIQUE,@CUR_CAT_IMPOSITION,@CUR_REGIME_FISCAL
       ,@CUR_REGIME_IMPOSITION,@CUR_DATE_ADHESION,@CUR_DATE_DEBUT_ACTIVITE,@CUR_DATE_DEBUT_1ER_EXO,@CUR_DATE_FIN_1ER_EXO,@CUR_DF_PRO_EXIST
       ,@CUR_OBSERVATION,@CUR_ABT_JOURNAL,@CUR_ID_SIT_FAM,@CUR_ID_STAT_CONJOINT,@CUR_ID_ADRESSE_ALTERNATIVE,@CUR_REGISTRE_COMMERCE
       ,@CUR_REGISTRE_METIERS,@CUR_ID_MOTIF_RADIATION,@CUR_ID_CASIER,@CUR_DATE_EFFET_RADIATION,@CUR_DEFAULT_NAF_STAT,@CUR_COMMENTAIRE_RADIATION
       ,@CUR_ID_TIERS_CLIENT,@CUR_DROIT_ENTREE,@CUR_DATE_RADIATION_ADM,@CUR_ID_MOTIF_EXONERATION_DROIT_ENTREE,@CUR_ID_PROFILE_ADHESION
       ,@CUR_DATE_CREATION,@CUR_LISTE_ANOMALIES,@CUR_ID_STATUT_ADM,@CUR_ID_AGENCE,'A' + @CUR_NUMERO_ADHERENT,@CUR_DATE_DERNIERE_MODIFICATION
       ,@CUR_ID_INTERLOCULTEUR_DERNIERE_MODIFICATION,@CUR_DESTINATAIRE_ATTESTATION,@CUR_NOMENCLATURE,@CUR_ID_CASIER_ATT,@CUR_TYPE_SUIVI
       ,@CUR_ID_ANALYSTE_REG,@CUR_ID_CASIER_ATT_SECONDAIRE,@CUR_GUID_ADHERENT,@CUR_HAS_DOSSIER_PGI,@CUR_NB_ASSOCIES,@CUR_NB_ASSOCIES_ACTIFS
       ,@CUR_ID_ACTEUR_TELETRANS,@CUR_ID_PARTENAIRE_SIE,@CUR_ROF,@CUR_TENUE_COMPTA_TTC,@CUR_ACTIVITE_NON_SOUMISE_TVA,@CUR_IS_EIRL,@CUR_DATE_OPTION_IS
       ,@CUR_CODE_TENUE_COMPTA,@CUR_CODE_EXIGIBILITE_TVA,@CUR_CODE_REGIME_TVA,@CUR_ID_BASE_IMPOSITION,@CUR_FRANCHISE_TVA,@CUR_GESTION_TVA_COR
       ,@CUR_ROF_TVA,@CUR_ASSUJETTI_PARTIEL_TVA,@CUR_WEB_BLOCAGE_ACCES,@CUR_WEB_OPTION_ECV,@CUR_WEB_OPTION_DG,@CUR_WEB_OPTION_CRM
       ,@CUR_ROF_CVAE,@CUR_TVA_NB_PERIODES_MANQUANTES,@CUR_MEDECIN_CODE_SECTEUR,@CUR_SCM_MEMBRE,@CUR_TVA_PRECOMPTE,@CUR_ACRE,@CUR_ACRE_DEBUT,@CUR_ACRE_FIN
       ,@CUR_EXO_CET,@CUR_EXO_AF,@CUR_EXO_CSG_CRDS,@CUR_EXO_RETRAITE,@CUR_EXO_MALADIE,@CUR_ACTIVITE_ACCESSOIRE,@CUR_TVA_DES,@CUR_DIPLOME_VERIFIE
       ,@CUR_DIPLOME_OBTENTION,@CUR_LOGICIEL_COMPTABLE,@CUR_ZFU_VERIFIEE,@CUR_ZFU_DATE_DEBUT,@CUR_ZFU_DATE_FIN,@CUR_ZFU_GENERATION
       ,@CUR_WEB_BLOCAGE_SAISIE_DF,@CUR_OBSERVATION_TVA,@CUR_LISTE_LOCAUX,@CUR_DATE_OBTENTION_LOC,@CUR_ROF_CFE,@CUR_WEB_DESACTIVATION_NOTIFICATION_MAIL
          ,@CUR_EXCLUSION_PORTAIL_TVA,@CUR_EXCLUSION_EXPORT_TVA_FCGA_OBS,@CUR_NB_OBLIGATIONS_FISCALES_LOC,@CUR_SOURCE_DOCUMENT_EPS,@CUR_SOURCE_COMPTABILITE_EPS,@COMPTABILITE_INFORMATISEE,1,@CUR_ID_BUREAU_OLD)

       set @_ID_ADHERENT = @@IDENTITY    


       -- Adresses DOM
       set @_ID_ADRESSE_DOM = null
       
       if @CUR_INTERNATIONALE_DOM is not null 
             begin 
       INSERT INTO #ADRESSES_TEMP
       (IDENTITE_DESTINATAIRE,COMPLEMENT_IDENTIFICATION,COMPLEMENT_ADRESSE
             ,NUMERO_VOIE,TYPE_VOIE,LIBELLE_VOIE,COMPLEMENT_ADRESSE_2,CP,INSEE,INTERNATIONALE
             ,COMPLEMENT_INTERNATIONAL,ID_PAYS,is_AtooCGA40)
       VALUES 
              (@CUR_IDENTITE_DESTINATAIRE_DOM,@CUR_COMPLEMENT_IDENTIFICATION_DOM,@CUR_COMPLEMENT_ADRESSE_DOM
       ,@CUR_NUMERO_VOIE_DOM,@CUR_TYPE_VOIE_DOM,@CUR_LIBELLE_VOIE_DOM,@CUR_COMPLEMENT_ADRESSE_2_DOM,@CUR_CP_DOM,@CUR_INSEE_DOM
             ,@CUR_INTERNATIONALE_DOM,@CUR_COMPLEMENT_INTERNATIONAL_DOM,@CUR_ID_PAYS_DOM,1)
       
       set @_ID_ADRESSE_DOM = @@IDENTITY
             end

       -- Personnes 
       INSERT INTO #PERSONNES_TEMP
(ID_TITRE,RAISON_SOCIALE,NOM,PRENOM,TELEPHONE_FIXE,TELEPHONE_MOBILE,TELEPHONE_FAX,EMAIL,TYPE_PERSONNE,ID_ADRESSE
       ,DATE_NAISSANCE,SITE_WEB,LOGIN_CGA,PASSWORD_CGA,TELEPHONE_ALTERNATIVE,NOM_JEUNE_FILLE,MUST_CHANGED_PASSWORD,ID_STATUT_EMAIL,EMAIL_CCI_LIST,is_AtooCGA40)
       VALUES
(@CUR_ID_TITRE,@CUR_RAISON_SOCIALE,@CUR_NOM,@CUR_PRENOM,@CUR_TELEPHONE_FIXE_PERSO,@CUR_TELEPHONE_MOBILE_PERSO,@CUR_TELEPHONE_FAX_PERSO,@CUR_EMAIL_PERSO
       ,@CUR_TYPE_PERSONNE,@_ID_ADRESSE_DOM,@CUR_DATE_NAISSANCE,@CUR_SITE_WEB,@CUR_LOGIN_CGA,@CUR_PASSWORD_CGA,@CUR_TELEPHONE_ALTERNATIVE_PERSO,@CUR_NOM_JEUNE_FILLE
             ,@CUR_MUST_CHANGED_PASSWORD,@CUR_ID_STATUT_EMAIL,@CUR_EMAIL_CCI_LIST,1)
       
       set @_ID_PERSONNE = @@IDENTITY


       --Fin comptes plan
       INSERT INTO #FIN_COMPT_PLAN_TEMP
             (COMPTE, LIBELLE, COMPTE_EXTERNE, is_AtooCGA40)
       VALUES 
             ('CA' + right ('00' + convert (varchar,@compteur),6),@CUR_LIBELLE, 'C0' +  right ('00' + convert (varchar,@compteur),6),1)

       -- Fin tiers
       INSERT INTO #FIN_TIERS_TEMP 
       (COMPTE, TYPE_TIERS, SOLDE, AUTOFACTURATION, RIB, INTRACOMMUNAUTAIRE, TITULAIRE_COMPTE, DOMICILIATION
       ,AUTORISATION_PRELEVEMENT, ID_PROFIL_FRS, MODE_REGLEMENT_PAR_DEFAUT, CHRONO_AUTOFACTURATION, ID_BLOCAGE_FACT
       , ID_DELAI_REGLEMENT, DATE_DEBUT_MANDAT_AUTOFACTURATION, DATE_FIN_MANDAT_AUTOFACTURATION, ADMINISTRATEUR, EXONERATION_TVA
       , PROFESSION, SOLDE_TC, IBAN, BIC, IBAN_ORIGINE, MANDAT_SEPA, DATE_SIGNATURE_MANDAT_SEPA, DATE_PREMIER_PRELEVEMENT, MANDAT_SEPA_ORIGINE, is_AtooCGA40)
       VALUES ('CA' + right ('00' + convert (varchar,@compteur),6), @CUR_TYPE_TIERS, @CUR_SOLDE, @CUR_AUTOFACTURATION, @CUR_RIB
       , @CUR_INTRACOMMUNAUTAIRE, @CUR_TITULAIRE_COMPTE, @CUR_DOMICILIATION,@CUR_AUTORISATION_PRELEVEMENT
       , @CUR_ID_PROFIL_FRS, @CUR_MODE_REGLEMENT_PAR_DEFAUT, @CUR_CHRONO_AUTOFACTURATION, @CUR_ID_BLOCAGE_FACT
       , @CUR_ID_DELAI_REGLEMENT, @CUR_DATE_DEBUT_MANDAT_AUTOFACTURATION, @CUR_DATE_FIN_MANDAT_AUTOFACTURATION, @CUR_ADMINISTRATEUR
       , @CUR_EXONERATION_TVA, @CUR_PROFESSION, @CUR_SOLDE_TC ,@CUR_IBAN,@CUR_BIC,@CUR_IBAN_ORIGINE
       , @CUR_MANDAT_SEPA,@CUR_DATE_SIGNATURE_MANDAT_SEPA,@CUR_DATE_PREMIER_PRELEVEMENT,@CUR_MANDAT_SEPA_ORIGINE,1)

       set @_ID_TIERS = @@IDENTITY

       -- Adresses PRO
       set @_ID_ADRESSE_PRO = null
       
       if @CUR_INTERNATIONALE_PRO is not null
             begin
       INSERT INTO #ADRESSES_TEMP
       (IDENTITE_DESTINATAIRE,COMPLEMENT_IDENTIFICATION,COMPLEMENT_ADRESSE
             ,NUMERO_VOIE,TYPE_VOIE,LIBELLE_VOIE,COMPLEMENT_ADRESSE_2,CP,INSEE,INTERNATIONALE
             ,COMPLEMENT_INTERNATIONAL,ID_PAYS,is_AtooCGA40)
       VALUES 
              (@CUR_IDENTITE_DESTINATAIRE_PRO,@CUR_COMPLEMENT_IDENTIFICATION_PRO,@CUR_COMPLEMENT_ADRESSE_PRO
       ,@CUR_NUMERO_VOIE_PRO,@CUR_TYPE_VOIE_PRO,@CUR_LIBELLE_VOIE_PRO,@CUR_COMPLEMENT_ADRESSE_2_PRO,@CUR_CP_PRO,@CUR_INSEE_PRO
             ,@CUR_INTERNATIONALE_PRO,@CUR_COMPLEMENT_INTERNATIONAL_PRO,@CUR_ID_PAYS_PRO,1)
       
       set @_ID_ADRESSE_PRO = @@IDENTITY
             end

	   		-- Adresses ALTERNATIVE
       set @_ID_ADRESSE_ALT = null
       
       if @CUR_INTERNATIONALE_ALT is not null 
             begin 
       INSERT INTO #ADRESSES_TEMP
       (IDENTITE_DESTINATAIRE,COMPLEMENT_IDENTIFICATION,COMPLEMENT_ADRESSE
             ,NUMERO_VOIE,TYPE_VOIE,LIBELLE_VOIE,COMPLEMENT_ADRESSE_2,CP,INSEE,INTERNATIONALE
             ,COMPLEMENT_INTERNATIONAL,ID_PAYS,is_AtooCGA40)
       VALUES 
              (
			  @CUR_IDENTITE_DESTINATAIRE_ALT,@CUR_COMPLEMENT_IDENTIFICATION_ALT,@CUR_COMPLEMENT_ADRESSE_ALT
       ,@CUR_NUMERO_VOIE_ALT,@CUR_TYPE_VOIE_ALT,@CUR_LIBELLE_VOIE_ALT,@CUR_COMPLEMENT_ADRESSE_2_ALT,@CUR_CP_ALT,@CUR_INSEE_ALT
             ,@CUR_INTERNATIONALE_ALT,@CUR_COMPLEMENT_INTERNATIONAL_ALT,@CUR_ID_PAYS_ALT,1)
       
       set @_ID_ADRESSE_ALT = @@IDENTITY
             end
       -- Etablissements
       INSERT INTO #ETABLISSEMENTS_TEMP
       (SIRET,ID_ADHERENT,ETBS_PRINCIPAL,NAF,ENSEIGNE,DATE_CREATION
       ,ID_ADRESSE,RIVOLI,EMAIL,TELEPHONE_FIXE,TELEPHONE_MOBILE,TELEPHONE_FAX
	   ,EFFECTIF,SURFACE_DE_VENTE,ACTIVITE_PRINCIPALE,ACTIVITE_SECONDAIRE,TELEPHONE_ALTERNATIVE,ROF_CFE,is_AtooCGA40)
       VALUES (@CUR_SIRET,@_ID_ADHERENT,@CUR_ETBS_PRINCIPAL,@CUR_NAF,@CUR_ENSEIGNE,@CUR_DATE_CREATION_ETAB
		,@_ID_ADRESSE_PRO
		,@CUR_RIVOLI,@CUR_EMAIL_ETAB,@CUR_TELEPHONE_FIXE_ETAB,@CUR_TELEPHONE_MOBILE_ETAB,@CUR_TELEPHONE_FAX_ETAB
		,@CUR_EFFECTIF,@CUR_SURFACE_DE_VENTE,@CUR_ACTIVITE_PRINCIPALE,@CUR_ACTIVITE_SECONDAIRE,@CUR_TELEPHONE_ALTERNATIVE_ETAB,@CUR_ROF_CFE_ETAB,1)

       set @_ID_ETABLISSEMENTS = @@IDENTITY
	   set @_ID_ADRESSE_ADR_ETAB = @_ID_ADRESSE_PRO



	   	-- Adresses et ETABLISSEMENTS secondaires
	   begin
	   if ((select COUNT(*) from AtooCGA40..ETABLISSEMENTS where AtooCGA40..ETABLISSEMENTS.ID_ADHERENT = @CUR_ID_ADHERENT and AtooCGA40..ETABLISSEMENTS.ETBS_PRINCIPAL = 0) > 0) 
             begin 
			 set @CUR_ID_ETABLISSEMENTS_SECONDAIRES =(select ID_ADRESSE from AtooCGA40..ETABLISSEMENTS where AtooCGA40..ETABLISSEMENTS.ID_ADHERENT = @CUR_ID_ADHERENT and AtooCGA40..ETABLISSEMENTS.ETBS_PRINCIPAL = 0 and AtooCGA40..ETABLISSEMENTS.ETBS_PRINCIPAL = 0 and AtooCGA40..ETABLISSEMENTS.ID_ADRESSE = @CUR_ID_ADRESSE_CORRESPONDANCE)

		-- Ajout Adresses des établissements
       INSERT INTO #ADRESSES_TEMP 
       (IDENTITE_DESTINATAIRE,COMPLEMENT_IDENTIFICATION,COMPLEMENT_ADRESSE
             ,NUMERO_VOIE,TYPE_VOIE,LIBELLE_VOIE,COMPLEMENT_ADRESSE_2,CP,INSEE,INTERNATIONALE
             ,COMPLEMENT_INTERNATIONAL,ID_PAYS,ID_OLD_ADRESSE,is_AtooCGA40)
		select 
			 ADR.IDENTITE_DESTINATAIRE
			 ,ADR.COMPLEMENT_IDENTIFICATION
			 ,ADR.COMPLEMENT_ADRESSE
             ,ADR.NUMERO_VOIE
			 ,ADR.TYPE_VOIE
			 ,ADR.LIBELLE_VOIE
			 ,ADR.COMPLEMENT_ADRESSE_2
			 ,ADR.CP
			 ,ADR.INSEE,INTERNATIONALE
             ,ADR.COMPLEMENT_INTERNATIONAL
			 ,ADR.ID_PAYS
			 ,ADR.ID_ADRESSE
			 ,1
			  from AtooCGA40..ETABLISSEMENTS ETABL
			  inner join AtooCGA40..ADRESSES ADR on ETABL.ID_ADRESSE = ADR.ID_ADRESSE
			  where ETABL.ID_ADHERENT = @CUR_ID_ADHERENT and ETABL.ETBS_PRINCIPAL = 0 and ADR.INTERNATIONALE = 0


		-- Ajout établissements secondaires
		INSERT INTO #ETABLISSEMENTS_TEMP
		(SIRET,ID_ADHERENT,ETBS_PRINCIPAL,NAF,ENSEIGNE,DATE_CREATION, ID_ADRESSE
		,RIVOLI,EMAIL,TELEPHONE_FIXE,TELEPHONE_MOBILE,TELEPHONE_FAX
		,EFFECTIF,SURFACE_DE_VENTE,ACTIVITE_PRINCIPALE,ACTIVITE_SECONDAIRE,TELEPHONE_ALTERNATIVE,ROF_CFE,is_AtooCGA40)
			select 
			SIRET
			,@_ID_ADHERENT
			,ETBS_PRINCIPAL
			,NAF
			,ENSEIGNE
			,DATE_CREATION
			,ADRT.ID_ADRESSE
			,RIVOLI
			,EMAIL
			,TELEPHONE_FIXE
			,TELEPHONE_MOBILE
			,TELEPHONE_FAX
			,EFFECTIF
			,SURFACE_DE_VENTE
			,ACTIVITE_PRINCIPALE
			,ACTIVITE_SECONDAIRE
			,TELEPHONE_ALTERNATIVE
			,ROF_CFE
			,1
			from AtooCGA40..ETABLISSEMENTS ETABL
			inner join #ADRESSES_TEMP ADRT on ADRT.ID_OLD_ADRESSE = ETABL.ID_ADRESSE
			where ETABL.ID_ADHERENT = @CUR_ID_ADHERENT and ETABL.ETBS_PRINCIPAL = 0
			
			--select * 
			--from AtooCGA40..ETABLISSEMENTS ETABL
			--inner join #ADRESSES_TEMP ADRT on ADRT.ID_OLD_ADRESSE = ETABL.ID_ADRESSE
			--where ETABL.ID_ADHERENT = 6 and ETABL.ETBS_PRINCIPAL = 0

            end
end

       --Mise à jour tables
       --update #ADHERENTS_TEMP set id_personne = @_ID_PERSONNE
       
       update #ADHERENTS_TEMP set id_personne = @_ID_PERSONNE where ID_ADHERENT_OLD = @CUR_ID_ADHERENT    --id_personne = @CUR_ID_PERSONNE  and is_AtooCGA40 = 1
       update #ADHERENTS_TEMP set ID_ADRESSE_ALTERNATIVE = @CUR_ID_ADRESSE_ALTERNATIVE where ID_ADHERENT_OLD = @CUR_ID_ADHERENT --where IS_AtooCGA40 = 1

       --update #PERSONNES_TEMP set id_adresse = @_ID_ADRESSE_DOM where id_adresse = @CUR_ID_ADRESSE_PERSO  and is_AtooCGA40 = 1 -- FAIT LORS DE LA CREATION DE PERSONNE
       update #ETABLISSEMENTS_TEMP set id_adresse = @_ID_ADRESSE_PRO where ID_ADHERENT = @_ID_ADHERENT and ETBS_PRINCIPAL = 1 --= id_adresse = @CUR_ID_ADRESSE_ETAB  
             
		set @_ID_ETABLISSEMENTS_SECONDAIRES =(select ID_ADRESSE from #ADRESSES_TEMP where id_old_adresse = @CUR_ID_ADRESSE_CORRESPONDANCE)

       -- Mise à jour de l'adresse de correspondance avec le nouvel ID_ADRESSE      
       update #ADHERENTS_TEMP set ID_ADRESSE_CORRESPONDANCE = case @CUR_ID_ADRESSE_CORRESPONDANCE 
             when @CUR_ID_ADRESSE_PERSO then @_ID_ADRESSE_DOM
             when @CUR_ID_ADRESSE_ALTERNATIVE then @_ID_ADRESSE_ALT
             when @CUR_ID_ETABLISSEMENTS_SECONDAIRES then @_ID_ETABLISSEMENTS_SECONDAIRES 
             when @CUR_ID_ADRESSE_PRO then @_ID_ADRESSE_PRO 
             when @CUR_ID_ADRESSE_ADR_ETAB then @_ID_ADRESSE_ADR_ETAB 
			 else @_ID_ADRESSE_PRO
		end 
         where ID_ADHERENT_OLD = @CUR_ID_ADHERENT
              and is_AtooCGA40 = 1

       -- Mise à jour de l'adresse de alternative avec le nouvel ID_ADRESSE      
        update #ADHERENTS_TEMP set ID_ADRESSE_ALTERNATIVE = case @CUR_ID_ADRESSE_ALTERNATIVE
             when @CUR_ID_ADRESSE_PERSO then @_ID_ADRESSE_DOM
             when @CUR_ID_ADRESSE_ALTERNATIVE then @_ID_ADRESSE_ALT
             when @CUR_ID_ETABLISSEMENTS_SECONDAIRES then @_ID_ETABLISSEMENTS_SECONDAIRES 
             when @CUR_ID_ADRESSE_PRO then @_ID_ADRESSE_PRO 
             when @CUR_ID_ADRESSE_ADR_ETAB then @_ID_ADRESSE_ADR_ETAB 
		end 
         where ID_ADHERENT_OLD = @CUR_ID_ADHERENT
              and is_AtooCGA40 = 1 AND @CUR_ID_ADRESSE_ALTERNATIVE IS NOT NULL
       
       
       
       update #ADHERENTS_TEMP set id_tiers_client = @_ID_TIERS where NUM_ADH_OLD = @CUR_NUMERO_ADHERENT  and is_AtooCGA40 = 1
       --update #ADHERENTS_TEMP set id_tiers_client = @_ID_TIERS where id_tiers_client = @CUR_ID_TIERS_CLIENT  and is_AtooCGA40 = 1
       



--     J] FIN REQUETE INJECTION

FETCH NEXT FROM ADHERENTS_cursor
       INTO @CUR_ID_ADHERENT,@CUR_NUMERO_ADHERENT,@CUR_ID_PERSONNE,@CUR_ID_ADRESSE_CORRESPONDANCE,@CUR_ID_ADRESSE_JOURNAL,@CUR_ID_BUREAU
       ,@CUR_ID_EXPERT,@CUR_ID_ANALYSTE_GESTION,@CUR_ID_ANALYSTE_ECV,@CUR_ID_GESTION_ADMIN,@CUR_ID_COLLABORATEUR,@CUR_ID_MOTIF_ADHESION
       ,@CUR_ID_STAT_ADHESION,@CUR_HORS_DELAI,@CUR_ID_COTISATION,@CUR_ID_FORME_JURIDIQUE,@CUR_CAT_IMPOSITION,@CUR_REGIME_FISCAL
       ,@CUR_REGIME_IMPOSITION,@CUR_DATE_ADHESION,@CUR_DATE_DEBUT_ACTIVITE,@CUR_DATE_DEBUT_1ER_EXO,@CUR_DATE_FIN_1ER_EXO,@CUR_DF_PRO_EXIST
       ,@CUR_OBSERVATION,@CUR_ABT_JOURNAL,@CUR_ID_SIT_FAM,@CUR_ID_STAT_CONJOINT,@CUR_ID_ADRESSE_ALTERNATIVE,@CUR_REGISTRE_COMMERCE
       ,@CUR_REGISTRE_METIERS,@CUR_ID_MOTIF_RADIATION,@CUR_ID_CASIER,@CUR_DATE_EFFET_RADIATION,@CUR_DEFAULT_NAF_STAT,@CUR_COMMENTAIRE_RADIATION
       ,@CUR_ID_TIERS_CLIENT,@CUR_DROIT_ENTREE,@CUR_DATE_RADIATION_ADM,@CUR_ID_MOTIF_EXONERATION_DROIT_ENTREE,@CUR_ID_PROFILE_ADHESION
       ,@CUR_DATE_CREATION,@CUR_LISTE_ANOMALIES,@CUR_ID_STATUT_ADM,@CUR_ID_AGENCE,@CUR_NUMERO_ADHERENT_AUXILIAIRE,@CUR_DATE_DERNIERE_MODIFICATION
       ,@CUR_ID_INTERLOCULTEUR_DERNIERE_MODIFICATION,@CUR_DESTINATAIRE_ATTESTATION,@CUR_NOMENCLATURE,@CUR_ID_CASIER_ATT,@CUR_TYPE_SUIVI
       ,@CUR_ID_ANALYSTE_REG,@CUR_ID_CASIER_ATT_SECONDAIRE,@CUR_GUID_ADHERENT,@CUR_HAS_DOSSIER_PGI,@CUR_NB_ASSOCIES,@CUR_NB_ASSOCIES_ACTIFS
	   ,@CUR_ID_ACTEUR_TELETRANS,@CUR_ID_PARTENAIRE_SIE,@CUR_ROF,@CUR_TENUE_COMPTA_TTC,@CUR_ACTIVITE_NON_SOUMISE_TVA,@CUR_IS_EIRL,@CUR_DATE_OPTION_IS
			 
			 --,@CUR_CADMINI,@CUR_FORMEJURIDIQUE
       ,@CUR_CODE_TENUE_COMPTA,@CUR_CODE_EXIGIBILITE_TVA,@CUR_CODE_REGIME_TVA,@CUR_ID_BASE_IMPOSITION,@CUR_FRANCHISE_TVA,@CUR_GESTION_TVA_COR
       ,@CUR_ROF_TVA,@CUR_ASSUJETTI_PARTIEL_TVA,@CUR_WEB_BLOCAGE_ACCES,@CUR_WEB_OPTION_ECV,@CUR_WEB_OPTION_DG,@CUR_WEB_OPTION_CRM
       ,@CUR_ROF_CVAE,@CUR_TVA_NB_PERIODES_MANQUANTES,@CUR_MEDECIN_CODE_SECTEUR,@CUR_SCM_MEMBRE,@CUR_TVA_PRECOMPTE,@CUR_ACRE,@CUR_ACRE_DEBUT,@CUR_ACRE_FIN
       ,@CUR_EXO_CET,@CUR_EXO_AF,@CUR_EXO_CSG_CRDS,@CUR_EXO_RETRAITE,@CUR_EXO_MALADIE,@CUR_ACTIVITE_ACCESSOIRE,@CUR_TVA_DES,@CUR_DIPLOME_VERIFIE
       ,@CUR_DIPLOME_OBTENTION,@CUR_LOGICIEL_COMPTABLE,@CUR_ZFU_VERIFIEE,@CUR_ZFU_DATE_DEBUT,@CUR_ZFU_DATE_FIN,@CUR_ZFU_GENERATION
       ,@CUR_WEB_BLOCAGE_SAISIE_DF,@CUR_OBSERVATION_TVA,@CUR_LISTE_LOCAUX,@CUR_DATE_OBTENTION_LOC,@CUR_ROF_CFE,@CUR_WEB_DESACTIVATION_NOTIFICATION_MAIL
             ,@CUR_EXCLUSION_PORTAIL_TVA,@CUR_EXCLUSION_EXPORT_TVA_FCGA_OBS,@CUR_NB_OBLIGATIONS_FISCALES_LOC, @CUR_SOURCE_DOCUMENT_EPS,@CUR_SOURCE_COMPTABILITE_EPS, @COMPTABILITE_INFORMATISEE,@CUR_ID_BUREAU_OLD
             ,@CUR_ID_ETABLISSEMENT
             ,@CUR_SIRET,@CUR_ID_ADHERENT,@CUR_ETBS_PRINCIPAL,@CUR_NAF,@CUR_ENSEIGNE,@CUR_DATE_CREATION_ETAB
       ,@CUR_ID_ADRESSE_ETAB,@CUR_RIVOLI,@CUR_EMAIL_ETAB,@CUR_TELEPHONE_FIXE_ETAB,@CUR_TELEPHONE_MOBILE_ETAB,@CUR_TELEPHONE_FAX_ETAB
       ,@CUR_EFFECTIF,@CUR_SURFACE_DE_VENTE,@CUR_ACTIVITE_PRINCIPALE,@CUR_ACTIVITE_SECONDAIRE,@CUR_TELEPHONE_ALTERNATIVE_ETAB,@CUR_ROF_CFE_ETAB,@CUR_ID_TIERS
             ,@CUR_COMPTE,@CUR_TYPE_TIERS,@CUR_SOLDE,@CUR_AUTOFACTURATION,@CUR_RIB
       ,@CUR_INTRACOMMUNAUTAIRE,@CUR_TITULAIRE_COMPTE,@CUR_DOMICILIATION,@CUR_AUTORISATION_PRELEVEMENT,@CUR_ID_PROFIL_FRS
       ,@CUR_MODE_REGLEMENT_PAR_DEFAUT,@CUR_CHRONO_AUTOFACTURATION,@CUR_ID_BLOCAGE_FACT,@CUR_ID_DELAI_REGLEMENT
       ,@CUR_DATE_DEBUT_MANDAT_AUTOFACTURATION,@CUR_DATE_FIN_MANDAT_AUTOFACTURATION,@CUR_ADMINISTRATEUR,@CUR_EXONERATION_TVA
       ,@CUR_PROFESSION,@CUR_SOLDE_TC,@CUR_IBAN,@CUR_BIC,@CUR_IBAN_ORIGINE,@CUR_MANDAT_SEPA,@CUR_DATE_SIGNATURE_MANDAT_SEPA
             ,@CUR_DATE_PREMIER_PRELEVEMENT,@CUR_MANDAT_SEPA_ORIGINE
            ,@CUR_COMPTE,@CUR_LIBELLE,@CUR_COMPTE_EXTERNE,@CUR_ID_ADRESSE_DOM,@CUR_IDENTITE_DESTINATAIRE_DOM
             ,@CUR_COMPLEMENT_IDENTIFICATION_DOM,@CUR_COMPLEMENT_ADRESSE_DOM
       ,@CUR_NUMERO_VOIE_DOM,@CUR_TYPE_VOIE_DOM,@CUR_LIBELLE_VOIE_DOM,@CUR_COMPLEMENT_ADRESSE_2_DOM,@CUR_CP_DOM
              ,@CUR_INSEE_DOM,@CUR_INTERNATIONALE_DOM,@CUR_COMPLEMENT_INTERNATIONAL_DOM,@CUR_ID_PAYS_DOM
       ,@CUR_ID_ADRESSE_PRO,@CUR_IDENTITE_DESTINATAIRE_PRO,@CUR_COMPLEMENT_IDENTIFICATION_PRO,@CUR_COMPLEMENT_ADRESSE_PRO
       ,@CUR_NUMERO_VOIE_PRO,@CUR_TYPE_VOIE_PRO,@CUR_LIBELLE_VOIE_PRO,@CUR_COMPLEMENT_ADRESSE_2_PRO,@CUR_CP_PRO
       ,@CUR_INSEE_PRO,@CUR_INTERNATIONALE_PRO,@CUR_COMPLEMENT_INTERNATIONAL_PRO,@CUR_ID_PAYS_PRO
			,@CUR_ID_PERSONNE,@CUR_ID_TITRE
       ,@CUR_RAISON_SOCIALE,@CUR_NOM,@CUR_PRENOM,@CUR_TELEPHONE_FIXE_PERSO,@CUR_TELEPHONE_MOBILE_PERSO,@CUR_TELEPHONE_FAX_PERSO
       ,@CUR_EMAIL_PERSO,@CUR_TYPE_PERSONNE,@CUR_ID_ADRESSE_PERSO,@CUR_DATE_NAISSANCE,@CUR_SITE_WEB,@CUR_LOGIN_CGA,@CUR_PASSWORD_CGA
       ,@CUR_TELEPHONE_ALTERNATIVE_PERSO,@CUR_NOM_JEUNE_FILLE,@CUR_MUST_CHANGED_PASSWORD,@CUR_ID_STATUT_EMAIL,@CUR_EMAIL_CCI_LIST

       ,@CUR_ID_ADRESSE_ALT,@CUR_IDENTITE_DESTINATAIRE_ALT,@CUR_COMPLEMENT_IDENTIFICATION_ALT,@CUR_COMPLEMENT_ADRESSE_ALT
       ,@CUR_NUMERO_VOIE_ALT,@CUR_TYPE_VOIE_ALT,@CUR_LIBELLE_VOIE_ALT,@CUR_COMPLEMENT_ADRESSE_2_ALT,@CUR_CP_ALT
       ,@CUR_INSEE_ALT,@CUR_INTERNATIONALE_ALT,@CUR_COMPLEMENT_INTERNATIONAL_ALT,@CUR_ID_PAYS_ALT

       ,@CUR_ID_ADRESSE_ADR_ETAB,@CUR_IDENTITE_DESTINATAIRE_ADR_ETAB,@CUR_COMPLEMENT_IDENTIFICATION_ADR_ETAB,@CUR_COMPLEMENT_ADRESSE_ADR_ETAB
       ,@CUR_NUMERO_VOIE_ADR_ETAB,@CUR_TYPE_VOIE_ADR_ETAB,@CUR_LIBELLE_VOIE_ADR_ETAB,@CUR_COMPLEMENT_ADRESSE_2_ADR_ETAB,@CUR_CP_ADR_ETAB
       ,@CUR_INSEE_ADR_ETAB,@CUR_INTERNATIONALE_ADR_ETAB,@CUR_COMPLEMENT_INTERNATIONAL_ADR_ETAB,@CUR_ID_PAYS_ADR_ETAB

END

CLOSE ADHERENTS_cursor
DEALLOCATE ADHERENTS_cursor

--select * from #PERSONNES_TEMP where is_AtooCGA40 = 1 

update #ETABLISSEMENTS_TEMP set NAF = null where NAF not in (
select NAF from AtooCGA40..ACTIVITES
where NOMENCLATURE = 'I'
)  and is_AtooCGA40 = 1





--Correspondance id_bureau effectué dans adhérents avec table de correspondance
update #ADHERENTS_TEMP set id_bureau = cb.id_bureau
--select cbc.BUR_CODE_SRC, cb.code_bur_old,*
	from #ADHERENTS_TEMP a
	inner join AtooPivot.._CAB_BUR_COMMUNS cbc on cbc.BUR_ID_SRC = a.ID_BUR_OLD --and (cbc.BUR_EXIST_IN_BOTH = 1)
	inner join  AtooCGA40..BUREAUX cb on cbc.BUR_CODE_SRC = cb.code_bur_old
	where 
	a.is_AtooCGA40 = '1' 
	--and NUM_ADH_OLD = 3343


--Correspondance ID_EXPERT effectué dans adhérents avec table de correspondance
update #ADHERENTS_TEMP set ID_EXPERT = cb.ID_EXPERT
--select *
	from #ADHERENTS_TEMP a
	--inner join AtooPivot.._CAB_BUR_COMMUNS cbc on cbc.BUR_ID_SRC = a.ID_BUR_OLD --and (cbc.BUR_EXIST_IN_BOTH = 1)
	inner join  AtooCGA40..EXPERTS cb on a.ID_EXPERT = cb.ID_EXP_OLD
	--inner join AtooPivot.._EXP_COMMUNS ec on ec.EXP_ID_EXPERT_SRC = a.ID_EXPERT --and ec.EXP_BUR_ID_SRC = a.ID_BUR_OLD --and ec.EXP_EXIST_IN_BOTH = 1
    where 
	a.is_AtooCGA40 = '1' --and A.numero_adherent = 15443
	--order by 7



--select * from AtooPivot.._EXP_COMMUNS ec where ec.EXP_NOM like '%GUILLAUME%'


	--select * from --AtooCGA40..exerce_pour ep
	----inner join 
	--AtooCGA40..experts e 
	--inner join AtooCGA40..personnes p on E.id_personne = p.id_personne
	--inner join AtooCGA40..EXERCE_POUR ep on Ep.ID_EXPERT = e.ID_EXPERT
	--where p.nom like '%CHABOSEAU%'

	--select * from --AtooCGA40..exerce_pour ep
	----inner join 
	--AtooCGA40..experts e 
	--inner join AtooCGA40..personnes p on E.id_personne = p.id_personne
	--inner join AtooCGA40..EXERCE_POUR ep on Ep.ID_EXPERT = e.ID_EXPERT
	--where p.nom like '%CHABOSEAU%'


	--select distinct e.ID_EXPERT from AtooCGA40..experts e, AtooCGA40..exerce_pour ep ,AtooCGA40..personnes p 
	--where E.id_personne = p.id_personne
	--and e.ID_EXPERT not in (select distinct ID_EXPERT from AtooCGA40..EXERCE_POUR)
	----and p.nom like '%GUILLAUME%'
	--orDer by 1


--Correspondance ID_COLLABORATEUR effectué dans adhérents avec table de correspondance
update #ADHERENTS_TEMP set ID_COLLABORATEUR = c.ID_COLLABORATEUR
	--select * 
	from #ADHERENTS_TEMP a
	inner join  AtooCGA40..COLLABORATEURS c on c.ID_COL_OLD = A.id_collaborateur
	--inner join AtooPivot.._COL_COMMUNS cc on cc.COL_ID_COLLABORATEUR_SRC = a.ID_COLLABORATEUR and cc.COL_BUR_ID_SRC = a.ID_BUR_OLD and cc.COL_EXIST_IN_BOTH = 1
	where 
	a.is_AtooCGA40 = '1'
	--and a.ID_BUR_OLD = 27


	update #ADHERENTS_TEMP set ID_BUREAU = null where ID_BUREAU = 0



--	select * from BUREAUX where NOM_BUREAU like 'exco - fso'
--	select * from AtooCGA40..BUREAUX where NOM_BUREAU like 'exco - fso'


--select * from #ADHERENTS_TEMP where NUMERO_ADHERENT = 15436
--select * from ADHERENTS where NUMERO_ADHERENT = 15436
--select * from AtooCGA40..ADHERENTS where NUMERO_ADHERENT = 3343
--select * from AtooCGA40..ADHERENTS where NUMERO_ADHERENT = 15436
--select * from AtooPivot.._CAB_BUR_COMMUNS where BUR_ID_SRC in (6) or BUR_ID_DST in (6)


update #ADHERENTS_TEMP set ID_COLLABORATEUR = 459 where ID_COLLABORATEUR = 347 and ID_BUREAU = 107 and is_AtooCGA40 = '1' 
update #ADHERENTS_TEMP set ID_COLLABORATEUR = 114 where ID_COLLABORATEUR = 264 and ID_BUREAU = 10 and is_AtooCGA40 = '1' 
update #ADHERENTS_TEMP set ID_COLLABORATEUR = 125 where ID_COLLABORATEUR = 110 and ID_BUREAU = 8 and is_AtooCGA40 = '1' 
update #ADHERENTS_TEMP set ID_COLLABORATEUR = 188 where ID_COLLABORATEUR = 157 and ID_BUREAU = 790 and is_AtooCGA40 = '1' 
update #ADHERENTS_TEMP set ID_COLLABORATEUR = null
where ID_COLLABORATEUR in (83,160,202,240,241,243,247,249,273,330,335,336/*,348,350,351,352,353*/)

------------
----select distinct ID_COLLABORATEUR from #ADHERENTS_TEMP where ID_COLLABORATEUR not in (select distinct ID_COLLABORATEUR from COLLABORATEURS) order by 1
----select * from AtooCGA40..BUREAUX where id_bureau  = 107
----select * from AtooCGA40..BUREAUX where id_bureau  = 107
--select ID_COLLABORATEUR,* from #ADHERENTS_TEMP where NUMERO_ADHERENT = 15473
--select * from AtooCGA40..COLLABORATEURS ct where [ID_COL_OLD] = 352
--select * from AtooCGA40..COLLABORATEURS where ID_COLLABORATEUR = 261
--select * from AtooPivot.._COL_COMMUNS cc where cc.COL_BUR_ID_SRC = 3
--select * from AtooPivot.._COL_COMMUNS cc where cc.COL_ID_COLLABORATEUR_SRC = 352

--select * from AtooPivot.._CAB_BUR_COMMUNS cc where cc.CAB_NUM_CAB_SRC = 10125


select * from #ADHERENTS_TEMP cc
where NUMERO_ADHERENT = '015411'  --and cc.is_AtooCGA40 = '1' 

--select * from AtooCGA40..ADHERENTS cc
--where NUMERO_ADHERENT = 3318

select * from AtooPivot.._CAB_BUR_COMMUNS cc where cc.CAB_REF_CAB_SRC = 10125
select * from BUREAUX cc where cc.CODE_BUR_OLD = 10125



select * from AtooCGA40..BUREAUX where NOM_BUREAU like '%cba%'
select * from AtooCGA40..BUREAUX where NOM_BUREAU like '%cba%'
select * from AtooCGA40..CABINETS_COMPTABLES cc where cc.NOM_CABINET like '%cba%'
select * from AtooCGA40..CABINETS_COMPTABLES cc where cc.NOM_CABINET like '%cba%'
select * from AtooCGA40..CHRONOS 

--select * from AtooCGA40.. COLLABORATEURS cc
--inner join AtooCGA40..PERSONNES p on cc.ID_PERSONNE=p.ID_PERSONNE
--where NOM like '%simian%'

--select * from AtooCGA40.. COLLABORATEURS cc
--inner join AtooCGA40..PERSONNES p on cc.ID_PERSONNE=p.ID_PERSONNE
--where NOM like '%simian%'

--select distinct ID_COLLABORATEUR from #ADHERENTS_TEMP where ID_COLLABORATEUR not in (select distinct AtooPivot.._COL_COMMUNS.COL_ID_COLLABORATEUR_SRC from AtooPivot.._COL_COMMUNS) order by 1

--select * from #ADHERENTS_TEMP where ID_BUREAU = 944 

-- rollback tran

--select * from AtooCGA40..BUREAUX where CODE_BUREAU like '10198'
--select * from AtooCGA40..BUREAUX where CODE_BUREAU like '10264'
--select * from #ADHERENTS_TEMP where ID_BUREAU = 944 
--select * from AtooPivot.._CAB_BUR_COMMUNS where BUR_ID_SRC = 944 --or BUR_ID_dst = 944
--select * from AtooCGA40..BUREAUX where nom_BUREAU like '%gascogne expertise%'

--select * from AtooPivot.._CAB_BUR_COMMUNS c where c. = 944 --or BUR_ID_dst = 944
  --CASIERS

	update #ADHERENTS_TEMP set ID_AGENCE = null where is_AtooCGA40 = '1'
	update #ADHERENTS_TEMP set id_casier = 41 where id_casier = 256 and is_AtooCGA40 = '1'
	update #ADHERENTS_TEMP set id_casier = 42 where id_casier = 257 and is_AtooCGA40 = '1'
	update #ADHERENTS_TEMP set id_casier = 45 where id_casier = 258 and is_AtooCGA40 = '1'
	update #ADHERENTS_TEMP set id_casier = 44 where id_casier = 259 and is_AtooCGA40 = '1'
	update #ADHERENTS_TEMP set DESTINATAIRE_ATTESTATION = 1 where is_AtooCGA40 = '1' and ID_BUREAU is not null 
	update #ADHERENTS_TEMP set DESTINATAIRE_ATTESTATION = 0 where is_AtooCGA40 = '1' and ID_BUREAU is null 
	update #ADHERENTS_TEMP set ID_CASIER_ATT = 1 where is_AtooCGA40 = '1' 
	update #ADHERENTS_TEMP set ID_CASIER_ATT_SECONDAIRE = null where is_AtooCGA40 = '1' 
	update #ADHERENTS_TEMP set ABT_JOURNAL = null where is_AtooCGA40 = '1' 


--INTERLOCUTEURS
	--UPDATE #ADHERENTS_TEMP set ID_ANALYSTE_GESTION = 27 where IS_AtooCGA40 = 1 and ID_ANALYSTE_GESTION = 7
	--UPDATE #ADHERENTS_TEMP set ID_ANALYSTE_ECV = 27 where IS_AtooCGA40 = 1 and ID_ANALYSTE_ECV =7
	--UPDATE #ADHERENTS_TEMP set ID_GESTION_ADMIN = 27 where IS_AtooCGA40 = 1 and ID_GESTION_ADMIN =7
	--UPDATE #ADHERENTS_TEMP set ID_ANALYSTE_REG = 27 where IS_AtooCGA40 = 1 and ID_ANALYSTE_REG =7
	--UPDATE #ADHERENTS_TEMP set ID_INTERLOCULTEUR_DERNIERE_MODIFICATION = 27 where IS_AtooCGA40 = 1 and ID_INTERLOCULTEUR_DERNIERE_MODIFICATION =7
	
	--UPDATE #ADHERENTS_TEMP set ID_ANALYSTE_GESTION = null where IS_AtooCGA40 = 1 
	--UPDATE #ADHERENTS_TEMP set ID_ANALYSTE_ECV = null where IS_AtooCGA40 = 1 
	--UPDATE #ADHERENTS_TEMP set ID_GESTION_ADMIN = null where IS_AtooCGA40 = 1
	--UPDATE #ADHERENTS_TEMP set ID_ANALYSTE_REG = null where IS_AtooCGA40 = 1
	--UPDATE #ADHERENTS_TEMP set ID_INTERLOCULTEUR_DERNIERE_MODIFICATION = null where IS_AtooCGA40 = 1
 
--select * from INTERLOCUTEURS             
--select ID_INTERLOCULTEUR_DERNIERE_MODIFICATION,ID_ANALYSTE_GESTION,ID_ANALYSTE_ECV,ID_GESTION_ADMIN,ID_ANALYSTE_REG , * from #ADHERENTS_TEMP where is_AtooCGA40 = 0  and (ID_INTERLOCULTEUR_DERNIERE_MODIFICATION is not null or ID_ANALYSTE_GESTION is not null or ID_ANALYSTE_ECV is not null or ID_GESTION_ADMIN is not null or ID_ANALYSTE_REG  is not null)


 --COTISATIONS   
          
	--update #ADHERENTS_TEMP set ID_COTISATION = '13' where is_AtooCGA40 = '1' and ID_COTISATION = 1
	--update #ADHERENTS_TEMP set ID_COTISATION = '14' where is_AtooCGA40 = '1' and ID_COTISATION = 10
	--update #ADHERENTS_TEMP set ID_COTISATION = '15' where is_AtooCGA40 = '1' and ID_COTISATION = 8
	--update #ADHERENTS_TEMP set ID_COTISATION = '16' where is_AtooCGA40 = '1' and ID_COTISATION = 11
	--update #ADHERENTS_TEMP set ID_COTISATION = '17' where is_AtooCGA40 = '1' and ID_COTISATION = 12
	--update #ADHERENTS_TEMP set ID_COTISATION = '18' where is_AtooCGA40 = '1' and ID_COTISATION = 9

	--select ID_COTISATION, * from #ADHERENTS_TEMP where is_AtooCGA40 = 1

	--update #ADHERENTS_TEMP set DESTINATAIRE_ATTESTATION = '0'

	update #PERSONNES_TEMP set LOGIN_CGA = '', PASSWORD_CGA = '' where is_AtooCGA40 = '1'
	
	--update #ADHERENTS_TEMP set DEFAULT_NAF_STAT = null where is_AtooCGA40 = '1'
--BEGIN TRAN


INSERT INTO AtooCGA40..FIN_COMPTES_PLAN
       (COMPTE, LIBELLE, COMPTE_EXTERNE)
       SELECT COMPTE, LIBELLE, COMPTE_EXTERNE
       FROM #FIN_COMPT_PLAN_TEMP
       WHERE IS_AtooCGA40= 1 AND COMPTE like 'CA%'
       
SET IDENTITY_INSERT [AtooCGA40].[dbo].[FIN_TIERS] ON

INSERT INTO AtooCGA40..FIN_TIERS
       (ID_TIERS, COMPTE, TYPE_TIERS, SOLDE, AUTOFACTURATION, RIB, INTRACOMMUNAUTAIRE, TITULAIRE_COMPTE, DOMICILIATION
       ,AUTORISATION_PRELEVEMENT, ID_PROFIL_FRS, MODE_REGLEMENT_PAR_DEFAUT, CHRONO_AUTOFACTURATION, ID_BLOCAGE_FACT
       , ID_DELAI_REGLEMENT, DATE_DEBUT_MANDAT_AUTOFACTURATION, DATE_FIN_MANDAT_AUTOFACTURATION, ADMINISTRATEUR, EXONERATION_TVA
       , PROFESSION, SOLDE_TC,  IBAN, BIC, IBAN_ORIGINE, MANDAT_SEPA, DATE_SIGNATURE_MANDAT_SEPA, DATE_PREMIER_PRELEVEMENT, MANDAT_SEPA_ORIGINE)
       SELECT ID_TIERS, COMPTE, TYPE_TIERS, SOLDE, AUTOFACTURATION, RIB, INTRACOMMUNAUTAIRE, TITULAIRE_COMPTE, DOMICILIATION
       ,AUTORISATION_PRELEVEMENT, ID_PROFIL_FRS, MODE_REGLEMENT_PAR_DEFAUT, CHRONO_AUTOFACTURATION, ID_BLOCAGE_FACT
       , ID_DELAI_REGLEMENT, DATE_DEBUT_MANDAT_AUTOFACTURATION, DATE_FIN_MANDAT_AUTOFACTURATION, ADMINISTRATEUR, EXONERATION_TVA
       , PROFESSION, SOLDE_TC,  IBAN, BIC, IBAN_ORIGINE, null, DATE_SIGNATURE_MANDAT_SEPA, DATE_PREMIER_PRELEVEMENT, MANDAT_SEPA
             FROM #FIN_TIERS_TEMP
             WHERE IS_AtooCGA40 = 1 AND TYPE_TIERS =  'CA'

SET IDENTITY_INSERT [AtooCGA40].[dbo].[FIN_TIERS] OFF


SET IDENTITY_INSERT [AtooCGA40].[dbo].[ADRESSES] ON

INSERT INTO AtooCGA40..ADRESSES
             (ID_ADRESSE,IDENTITE_DESTINATAIRE,COMPLEMENT_IDENTIFICATION,COMPLEMENT_ADRESSE
             ,NUMERO_VOIE,TYPE_VOIE,LIBELLE_VOIE,COMPLEMENT_ADRESSE_2,CP,INSEE,INTERNATIONALE
             ,COMPLEMENT_INTERNATIONAL,ID_PAYS)
       SELECT 
             ID_ADRESSE,IDENTITE_DESTINATAIRE,COMPLEMENT_IDENTIFICATION,COMPLEMENT_ADRESSE
             ,NUMERO_VOIE,TYPE_VOIE,LIBELLE_VOIE,COMPLEMENT_ADRESSE_2,CP,INSEE,INTERNATIONALE
             ,COMPLEMENT_INTERNATIONAL,ID_PAYS
       FROM #ADRESSES_TEMP
             WHERE IS_AtooCGA40 = 1

SET IDENTITY_INSERT [AtooCGA40].[dbo].[ADRESSES] OFF

SET IDENTITY_INSERT [AtooCGA40].[dbo].[PERSONNES] ON

INSERT INTO AtooCGA40..PERSONNES
(ID_PERSONNE,ID_TITRE,RAISON_SOCIALE,NOM,PRENOM,TELEPHONE_FIXE,TELEPHONE_MOBILE,TELEPHONE_FAX,EMAIL,TYPE_PERSONNE,ID_ADRESSE
       ,DATE_NAISSANCE,SITE_WEB,LOGIN_CGA,PASSWORD_CGA,TELEPHONE_ALTERNATIVE,NOM_JEUNE_FILLE,MUST_CHANGED_PASSWORD,ID_STATUT_EMAIL,EMAIL_CCI_LIST)
       SELECT ID_PERSONNE,ID_TITRE,RAISON_SOCIALE,NOM,PRENOM,TELEPHONE_FIXE,TELEPHONE_MOBILE,TELEPHONE_FAX,EMAIL,TYPE_PERSONNE,ID_ADRESSE
       ,DATE_NAISSANCE,SITE_WEB,LOGIN_CGA,PASSWORD_CGA,TELEPHONE_ALTERNATIVE,NOM_JEUNE_FILLE,MUST_CHANGED_PASSWORD,ID_STATUT_EMAIL,EMAIL_CCI_LIST
       FROM #PERSONNES_TEMP
       WHERE IS_AtooCGA40 = 1

SET IDENTITY_INSERT [AtooCGA40].[dbo].[PERSONNES] OFF


SET IDENTITY_INSERT [AtooCGA40].[dbo].[ADHERENTS] ON

INSERT INTO AtooCGA40..ADHERENTS
      (ID_ADHERENT,NUMERO_ADHERENT,ID_PERSONNE,ID_ADRESSE_CORRESPONDANCE,ID_ADRESSE_JOURNAL,ID_BUREAU,ID_BUREAU_OLD
          ,ID_EXPERT,ID_ANALYSTE_GESTION,ID_ANALYSTE_ECV,ID_GESTION_ADMIN,ID_COLLABORATEUR,ID_MOTIF_ADHESION
              ,ID_STAT_ADHESION,HORS_DELAI,ID_COTISATION,ID_FORME_JURIDIQUE,CAT_IMPOSITION,REGIME_FISCAL
       ,REGIME_IMPOSITION,DATE_ADHESION,DATE_DEBUT_ACTIVITE,DATE_DEBUT_1ER_EXO,DATE_FIN_1ER_EXO,DF_PRO_EXIST
              ,OBSERVATION,ABT_JOURNAL,ID_SIT_FAM,ID_STAT_CONJOINT,ID_ADRESSE_ALTERNATIVE,REGISTRE_COMMERCE
       ,REGISTRE_METIERS,ID_MOTIF_RADIATION,ID_CASIER,DATE_EFFET_RADIATION,DEFAULT_NAF_STAT,COMMENTAIRE_RADIATION
       ,ID_TIERS_CLIENT,DROIT_ENTREE,DATE_RADIATION_ADM,ID_MOTIF_EXONERATION_DROIT_ENTREE,ID_PROFILE_ADHESION
       ,DATE_CREATION,LISTE_ANOMALIES,ID_STATUT_ADM,ID_AGENCE,NUMERO_ADHERENT_AUXILIAIRE,DATE_DERNIERE_MODIFICATION
       ,ID_INTERLOCULTEUR_DERNIERE_MODIFICATION,DESTINATAIRE_ATTESTATION,NOMENCLATURE,ID_CASIER_ATT,TYPE_SUIVI
       ,ID_ANALYSTE_REG,ID_CASIER_ATT_SECONDAIRE,GUID_ADHERENT,HAS_DOSSIER_PGI,NB_ASSOCIES,NB_ASSOCIES_ACTIFS
              ,ID_ACTEUR_TELETRANS,ID_PARTENAIRE_SIE,ROF,TENUE_COMPTA_TTC,ACTIVITE_NON_SOUMISE_TVA,IS_EIRL
       ,DATE_OPTION_IS,CODE_TENUE_COMPTA,CODE_EXIGIBILITE_TVA,CODE_REGIME_TVA,ID_BASE_IMPOSITION,FRANCHISE_TVA
       ,GESTION_TVA_COR,ROF_TVA,ASSUJETTI_PARTIEL_TVA,WEB_BLOCAGE_ACCES,WEB_OPTION_ECV,WEB_OPTION_DG,WEB_OPTION_CRM
       ,ROF_CVAE,TVA_NB_PERIODES_MANQUANTES,MEDECIN_CODE_SECTEUR,SCM_MEMBRE,TVA_PRECOMPTE,ACRE,ACRE_DEBUT,ACRE_FIN
           ,EXO_CET,EXO_AF,EXO_CSG_CRDS,EXO_RETRAITE,EXO_MALADIE,ACTIVITE_ACCESSOIRE,TVA_DES,DIPLOME_VERIFIE
              ,DIPLOME_OBTENTION,LOGICIEL_COMPTABLE,ZFU_VERIFIEE,ZFU_DATE_DEBUT,ZFU_DATE_FIN,ZFU_GENERATION
              ,WEB_BLOCAGE_SAISIE_DF,NUM_ADH_OLD,OBSERVATION_TVA,LISTE_LOCAUX,DATE_OBTENTION_LOC,ROF_CFE
       ,WEB_DESACTIVATION_NOTIFICATION_MAIL,EXCLUSION_PORTAIL_TVA,EXCLUSION_EXPORT_TVA_FCGA_OBS,NB_OBLIGATIONS_FISCALES_LOC,SOURCE_DOCUMENT_EPS,SOURCE_COMPTABILITE_EPS,COMPTABILITE_INFORMATISEE)
       SELECT ID_ADHERENT,NUMERO_ADHERENT,ID_PERSONNE,ID_ADRESSE_CORRESPONDANCE,NULL,ID_BUREAU,ID_BUREAU_OLD
          ,ID_EXPERT,ID_ANALYSTE_GESTION,ID_ANALYSTE_ECV,ID_GESTION_ADMIN,ID_COLLABORATEUR,ID_MOTIF_ADHESION
              ,ID_STAT_ADHESION,HORS_DELAI,ID_COTISATION,ID_FORME_JURIDIQUE,CAT_IMPOSITION,REGIME_FISCAL
       ,REGIME_IMPOSITION,DATE_ADHESION,DATE_DEBUT_ACTIVITE,DATE_DEBUT_1ER_EXO,DATE_FIN_1ER_EXO,DF_PRO_EXIST
             ,OBSERVATION,ABT_JOURNAL,ID_SIT_FAM,ID_STAT_CONJOINT,ID_ADRESSE_ALTERNATIVE,REGISTRE_COMMERCE
       ,REGISTRE_METIERS,ID_MOTIF_RADIATION,ID_CASIER,DATE_EFFET_RADIATION,DEFAULT_NAF_STAT,COMMENTAIRE_RADIATION
       ,ID_TIERS_CLIENT,DROIT_ENTREE,DATE_RADIATION_ADM,ID_MOTIF_EXONERATION_DROIT_ENTREE,ID_PROFILE_ADHESION
       ,DATE_CREATION,LISTE_ANOMALIES,ID_STATUT_ADM,ID_AGENCE,NUMERO_ADHERENT_AUXILIAIRE,DATE_DERNIERE_MODIFICATION
       ,ID_INTERLOCULTEUR_DERNIERE_MODIFICATION,DESTINATAIRE_ATTESTATION,NOMENCLATURE,ID_CASIER_ATT,TYPE_SUIVI
       ,ID_ANALYSTE_REG,ID_CASIER_ATT_SECONDAIRE,GUID_ADHERENT,HAS_DOSSIER_PGI,NB_ASSOCIES,NB_ASSOCIES_ACTIFS
              ,ID_ACTEUR_TELETRANS,ID_PARTENAIRE_SIE,ROF,TENUE_COMPTA_TTC,ACTIVITE_NON_SOUMISE_TVA,IS_EIRL
       ,DATE_OPTION_IS,CODE_TENUE_COMPTA,CODE_EXIGIBILITE_TVA,CODE_REGIME_TVA,ID_BASE_IMPOSITION,FRANCHISE_TVA
       ,GESTION_TVA_COR,ROF_TVA,ASSUJETTI_PARTIEL_TVA,WEB_BLOCAGE_ACCES,WEB_OPTION_ECV,WEB_OPTION_DG,WEB_OPTION_CRM
       ,ROF_CVAE,TVA_NB_PERIODES_MANQUANTES,MEDECIN_CODE_SECTEUR,SCM_MEMBRE,TVA_PRECOMPTE,ACRE,ACRE_DEBUT,ACRE_FIN
           ,EXO_CET,EXO_AF,EXO_CSG_CRDS,EXO_RETRAITE,EXO_MALADIE,ACTIVITE_ACCESSOIRE,TVA_DES,DIPLOME_VERIFIE
              ,DIPLOME_OBTENTION,LOGICIEL_COMPTABLE,ZFU_VERIFIEE,ZFU_DATE_DEBUT,ZFU_DATE_FIN,ZFU_GENERATION
              ,WEB_BLOCAGE_SAISIE_DF,NUM_ADH_OLD,OBSERVATION_TVA,LISTE_LOCAUX,DATE_OBTENTION_LOC,ROF_CFE
       ,WEB_DESACTIVATION_NOTIFICATION_MAIL,EXCLUSION_PORTAIL_TVA,EXCLUSION_EXPORT_TVA_FCGA_OBS,NB_OBLIGATIONS_FISCALES_LOC,SOURCE_DOCUMENT_EPS,SOURCE_COMPTABILITE_EPS,COMPTABILITE_INFORMATISEE
       FROM #ADHERENTS_TEMP
       WHERE IS_AtooCGA40 = 1


SET IDENTITY_INSERT [AtooCGA40].[dbo].[ADHERENTS] OFF


SET IDENTITY_INSERT [AtooCGA40].[dbo].[ETABLISSEMENTS] ON

INSERT INTO AtooCGA40..ETABLISSEMENTS
       (ID_ETABLISSEMENT, SIRET,ID_ADHERENT,ETBS_PRINCIPAL,NAF,ENSEIGNE,DATE_CREATION
       ,ID_ADRESSE,RIVOLI,EMAIL,TELEPHONE_FIXE,TELEPHONE_MOBILE,TELEPHONE_FAX
       ,EFFECTIF,SURFACE_DE_VENTE,ACTIVITE_PRINCIPALE,ACTIVITE_SECONDAIRE,TELEPHONE_ALTERNATIVE)
       SELECT ID_ETABLISSEMENT,SIRET,ID_ADHERENT,ETBS_PRINCIPAL,NAF,ENSEIGNE,DATE_CREATION
       ,ID_ADRESSE,RIVOLI,EMAIL,TELEPHONE_FIXE,TELEPHONE_MOBILE,TELEPHONE_FAX
       ,EFFECTIF,SURFACE_DE_VENTE,ACTIVITE_PRINCIPALE,ACTIVITE_SECONDAIRE,TELEPHONE_ALTERNATIVE
       FROM #ETABLISSEMENTS_TEMP
       WHERE IS_AtooCGA40 = 1

SET IDENTITY_INSERT [AtooCGA40].[dbo].[ETABLISSEMENTS] OFF



-- select p.NOM,p.PRENOM,* from AtooCGA40..adherents c
--inner join AtooCGA40..PERSONNES p on c.ID_PERSONNE = p.ID_PERSONNE
-- where NOM in ('castets')

-- select p.NOM,p.PRENOM,* from #ADHERENTS_TEMP c
--inner join PERSONNES p on c.ID_PERSONNE = p.ID_PERSONNE
-- where NOM in ('castets')



-- select p.NOM,* from EXPERTS c
--inner join PERSONNES p on c.ID_PERSONNE = p.ID_PERSONNE
-- where ID_EXPERT = 31

-- select p.NOM,* from AtooCGA40..EXPERTS c
--inner join AtooCGA40..PERSONNES p on c.ID_PERSONNE = p.ID_PERSONNE
-- where ID_EXPERT = 31

--select p.NOM,* from AtooPivot.._EXP_COMMUNS c
--inner join AtooCGA40..EXPERTS e on c.EXP_ID_EXPERT_SRC = e.ID_EXPERT
--inner join AtooCGA40..EXERCE_POUR ep on ep.ID_EXPERT = e.ID_EXPERT
--inner join AtooCGA40..PERSONNES p on e.ID_PERSONNE = p.ID_PERSONNE
--inner join AtooPivot.._CAB_BUR_COMMUNS cbc on ep.ID_BUREAU = cbc.BUR_ID_SRC
-- where c.EXP_ID_EXPERT_SRC = 31

-- select p.NOM,* from AtooPivot.._EXP_COMMUNS c
--inner join AtooCGA40..EXPERTS e on c.EXP_ID_EXPERT_SRC = e.ID_EXPERT
--inner join AtooCGA40..EXERCE_POUR ep on ep.ID_EXPERT = e.ID_EXPERT
--inner join AtooCGA40..PERSONNES p on e.ID_PERSONNE = p.ID_PERSONNE
--inner join AtooPivot.._CAB_BUR_COMMUNS cbc on ep.ID_BUREAU = cbc.BUR_ID_DST
-- where c.EXP_ID_EXPERT_DST = 34

-- select * from EXERCE_POUR where ID_EXPERT = 34
-- select * from AtooCGA40..EXERCE_POUR where ID_EXPERT = 31


-- select p.NOM,* from AtooPivot.._EXP_COMMUNS c
--inner join AtooCGA40..PERSONNES p on c.ID_PERSONNE = p.ID_PERSONNE
-- where c.EXP_BUR_ID_SRC = 31



-- ROLLBACK TRAN
-- COMMIT TRAN