select top 1 
cc.NUMERO_CABINET as CAB_REF_DST, 
cc.REF_CABINET as CAB_REF_SRC,
b.PRINCIPAL as CAB_IS_FUSION,
b.id_bureau as BUR_ID_DST,
b.id_bureau as BUR_ID_SRC,
b.NUMERO_CABINET as BUR_NUM_CAB_DST,
b.NUMERO_CABINET as BUR_NUM_CAB_SRC,
b.CODE_BUREAU as BUR_CODE_DST,
b.CODE_BUR_OLD as BUR_CODE_SRC,
b.NOM_BUREAU as BUR_NOM_BUR_DST,
b.NOM_BUREAU as BUR_NOM_BUR_SRC,
b.PRINCIPAL as BUR_IS_PRINCIPAL_DST,
b.PRINCIPAL as BUR_IS_PRINCIPAL_SRC,
b.PRINCIPAL as BUR_IS_FUSION,
ep.ID_BUREAU as EX_POUR_ID_BUR_DST,
ep.ID_BUR_OLD as EX_POUR_ID_BUR_SRC,
ep.ID_EXPERT as EX_POUR_ID_EXP_DST,
ep.ID_EXP_OLD as EX_POUR_ID_EXP_SRC,
b.PRINCIPAL as EX_POUR_IS_FUSION,
e.ID_EXPERT as EXP_ID_EXPERT_DST,
e.ID_EXP_OLD as EXP_ID_EXPERT_SRC,
b.PRINCIPAL as EXP_IS_FUSION,
c.ID_COLLABORATEUR as COL_ID_COL_DST,
c.ID_COLLABORATEUR as COL_ID_COL_SRC,
c.ID_COLLABORATEUR as COL_ID_BUR_DST,
c.ID_COLLABORATEUR as COL_ID_BUR_SRC,
b.PRINCIPAL as COL_IS_FUSION,
p.ID_PERSONNE as PERS_ID_SRC,
p.NOM as PERS_NOM_SRC,
p.PRENOM as PERS_PRENOM_SRC,
b.PRINCIPAL as PERS_IS_FUSION,
a.ID_ADHERENT as ADH_ID_DST,
a.ID_ADHERENT as ADH_ID_SRC,
a.NUMERO_ADHERENT as ADH_NUM_DST,
a.NUM_ADH_OLD as ADH_NUM_SRC,
b.PRINCIPAL as ADH_IS_FUSION,
ass.ID_ASSOCIE as ASS_ID_DST,
ass.ID_ASS_OLD as ASS_ID_SRC,
ass.ID_ADHERENT as ASS_ID_ADH_SRC,
b.PRINCIPAL as ASS_IS_FUSION,
je.ID_ECHANGE as EVT_ID_ECH_DST,
je.ID_ECHANGE as EVT_ID_ECH_SRC,
je.ID_SOURCE_ECHANGE as EVT_ID_SRC_ECH_DST,
je.ID_SOURCE_ECHANGE as EVT_ID_SRC_ECH_SRC,
je.ID_NATURE_ECHANGE as EVT_ID_NAT_ECH_DST,
je.ID_SOURCE_ECHANGE as EVT_ID_NAT_ECH_SRC,
je.ID_ECHANGE_PARENT as EVT_ID_ECH_PARENT_DST,
je.ID_ECHANGE_PARENT as EVT_ID_ECH_PARENT_SRC,
je.TYPE_ACTEUR as EVT_TYPE_ACTEUR_DST,
je.TYPE_ACTEUR as EVT_TYPE_ACTEUR_SRC,
b.PRINCIPAL as EVT_IS_FUSION,
jep.ID_ECHANGE as EVTPJ_ID_ECH_DST,
jep.ID_ECHANGE as EVTPJ_ID_ECH_SRC,
b.PRINCIPAL as EVTPJ_IS_FUSION,
m.ID_ADHERENT as MAND_ID_ADH_DST,
m.ID_ADHERENT as MAND_ID_ADH_SRC,
b.PRINCIPAL as MAND_IS_FUSION,
mecv.ID_ADHERENT as MAND_ECV_ID_ADH_DST,
mecv.ID_ADHERENT as MAND_ECV_ID_ADH_SRC,
b.PRINCIPAL as MAND_ECV_IS_FUSION,
t.ID_TABLEX as TAB_ID_TAB_DST,
t.ID_TABLEX as TAB_ID_TAB_SRC,
t.ID_ADHERENT as TAB_ID_ADH_DST,
t.ID_ADHERENT as TAB_ID_ADH_SRC,
t.ID_BUREAU as TAB_ID_BUR_DST,
t.ID_BUREAU as TAB_ID_BUR_SRC,
t.ID_COLLABORATEUR as TAB_ID_COL_DST,
t.ID_COLLABORATEUR as TAB_ID_COL_SRC,
t.ID_EXPERT as TAB_ID_EXP_DST,
t.ID_EXPERT as TAB_ID_EXP_SRC,
b.PRINCIPAL as TAB_IS_FUSION,
tt.ID_TABLEX_TVA as TABTVA_ID_TAB_DST,
tt.ID_TABLEX_TVA as TABTVA_ID_TAB_SRC,
tt.ID_ADHERENT as TABTVA_ID_ADH_DST,
tt.ID_ADHERENT as TABTVA_ID_ADH_SRC,
tt.ID_BUREAU as TABTVA_ID_BUR_DST,
tt.ID_BUREAU as TABTVA_ID_BUR_SRC,
tt.ID_COLLABORATEUR as TABTVA_ID_COL_DST,
tt.ID_COLLABORATEUR as TABTVA_ID_COL_SRC,
tt.ID_EXPERT as TABTVA_ID_EXP_DST,
tt.ID_EXPERT as TABTVA_ID_EXP_SRC,
b.PRINCIPAL as TABTVA_IS_FUSION
into AtooPivot..REFERRER
from CABINETS_COMPTABLES cc
inner join BUREAUX b on cc.REF_CABINET = cc.NUMERO_CABINET
inner join EXERCE_POUR ep on ep.ID_BUREAU = b.ID_BUREAU
inner join EXPERTS e on ep.ID_EXPERT = e.ID_EXPERT
inner join COLLABORATEURS c on c.ID_BUREAU = b.ID_BUREAU
inner join PERSONNES p on p.ID_PERSONNE = e.ID_PERSONNE
inner join ADHERENTS a on a.ID_BUREAU = b.ID_bureau
inner join ASSOCIES ass on p.ID_PERSONNE = ass.ID_PERSONNE
inner join JOURNAL_ECHANGES je on je.ID_ACTEUR = a.ID_ADHERENT
inner join JOURNAL_ECHANGES_PJ jep on jep.ID_ECHANGE = je.ID_ECHANGE
inner join MANDATS m on m.ID_ADHERENT = a.ID_ADHERENT
inner join MANDATS_ECV mecv on mecv.ID_ADHERENT = a.ID_ADHERENT
inner join TABLEX t on t.ID_ADHERENT = a.ID_ADHERENT
inner join TABLEX_TVA tt on tt.ID_ADHERENT = a.ID_ADHERENT
where b.ID_BUREAU = 1



